Repository remix-project-org/remix-project, pull requests merged in 2021-11, with the labels that each got.

#1720 Fix broken workspace UI
  apps/remix-ide/src/app/files/fileManager.js
  apps/remix-ide/src/app/files/workspaceFileProvider.js
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
Labels: fix

#1725 normalize file path only if exists
  apps/remix-ide/src/app/files/fileManager.js
Labels: bugfix

#1747 Show registered context menu items for both browser and localhost
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
Labels: fix

#1771 Fix custom id
  apps/remix-ide/src/app/tabs/runTab/contractDropdown.js
Labels: publish

#1781 publish latest libs
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-lib/package.json
  libs/remix-simulator/package.json
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-url-resolver/package.json
Labels: publish

#1782 Published latest remixd
  libs/remixd/package.json
Labels: publish

#1788 add auto closing brackets
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: fix

#1754 Fastcircle
  .circleci/config.yml
  .gitignore
  apps/remix-ide-e2e/nightwatch.ts
  apps/remix-ide-e2e/seleniumConfig.js
  apps/remix-ide-e2e/src/buildGroupTests.js
  apps/remix-ide-e2e/src/checkGroupTests.js
  apps/remix-ide-e2e/src/commands/clearConsole.ts
  apps/remix-ide-e2e/src/commands/clearTransactions.ts
  apps/remix-ide-e2e/src/helpers/buildgrouptest.ts
  apps/remix-ide-e2e/src/select_tests.sh
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.test.ts
  apps/remix-ide-e2e/src/tests/compiler_api.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/editor.spec.ts
  apps/remix-ide-e2e/src/tests/fileManager_api.test.ts
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide-e2e/src/tests/gist.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide-e2e/src/tests/recorder.test.ts
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
  apps/remix-ide-e2e/src/tests/solidityImport_group1.spec.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide-e2e/src/tests/specialFunctions.test.ts
  apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  apps/remix-ide-e2e/src/tests/verticalIconsPanel.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/ci/browser_test.sh
  apps/remix-ide/ci/browser_tests.sh
  apps/remix-ide/ci/browser_tests_chrome_1.sh
  apps/remix-ide/ci/browser_tests_firefox_1.sh
  apps/remix-ide/ci/browser_tests_firefox_2.sh
  apps/remix-ide/ci/browser_tests_plugin_api.sh
  apps/remix-ide/ci/browser_tests_run_deploy.sh
  apps/remix-ide/ci/lint.sh
  apps/solidity-compiler/src/app/app.tsx
  apps/solidity-compiler/src/app/compiler-api.ts
  apps/solidity-compiler/src/app/compiler.ts
  apps/solidity-compiler/src/environments/environment.prod.ts
  apps/solidity-compiler/src/environments/environment.ts
  apps/solidity-compiler/src/index.ts
  apps/solidity-compiler/src/main.tsx
  apps/solidity-compiler/src/polyfills.ts
  libs/remix-ui/clipboard/jest.config.js
  libs/remix-ui/clipboard/src/index.ts
  libs/remix-ui/utils/jest.config.js
  package-lock.json
  package.json
Labels: autosquash

#1812 Await localhost disconnection before switching to workspace
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: publish

#1797 Do not render if the file is already switched to
  apps/remix-ide/src/app/editor/editor.js
Labels: publish

#1813 run monaco from assets
  apps/remix-ide/webpack.config.js
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  package-lock.json
  package.json
Labels: bug, publish
