Repository remix-project-org/remix-project, pull requests merged in 2021-08, with the labels that each got.

#1481 Update blockchain.js
  apps/remix-ide/src/blockchain/blockchain.js
Labels: remix-beta

#1478 fix deploying, defining a correct type
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-lib/package.json
  libs/remix-lib/src/execution/txRunnerWeb3.ts
  libs/remix-simulator/package.json
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  package-lock.json
  package.json
Labels: remix-beta

#1483 fix checkbox on mainnet dialog
  apps/remix-ide/src/app/ui/confirmDialog.js
Labels: bugfix

#1487 linked the label to the checkbox
  apps/remix-ide/src/app/ui/confirmDialog.js
Labels: autorebase

#1518 Update shell commands with production build files
  apps/remix-ide/ci/deploy_from_travis_remix-alpha.sh
  apps/remix-ide/ci/deploy_from_travis_remix-beta.sh
  apps/remix-ide/ci/deploy_from_travis_remix-live.sh
Labels: performance
