Repository remix-project-org/remix-project, pull requests merged in 2021-01, with the labels that each got.

#694 Fixes for the debugger
  apps/remix-ide/src/app/compiler/compiler-helpers.js
  apps/remix-ide/src/app/compiler/compiler-imports.js
  apps/remix-ide/src/app/compiler/compiler-sourceVerifier-fetchAndCompile.js
  apps/remix-ide/src/app/tabs/debugger-tab.js
  libs/remix-debug/src/code/breakpointManager.ts
  libs/remix-debug/src/debugger/debugger.ts
  libs/remix-debug/src/solidity-decoder/internalCallTree.ts
  libs/remix-debug/src/trace/traceHelper.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
Labels: fix

#713 fix handlers reference
  apps/remix-ide/src/app/compiler/compiler-imports.js
Labels: bug

#719 'this' reference fixed in remix-lib
  libs/remix-lib/src/web3Provider/web3VmProvider.ts
Labels: remix-lib

#709 fix Recorder e2e tests
  apps/remix-ide-e2e/src/commands/createContract.ts
  apps/remix-ide-e2e/src/commands/selectContract.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/libraryDeployment.test.ts
  apps/remix-ide-e2e/src/tests/recorder.test.ts
Labels: autosquash

#731 unit tests for remix-tests CLI usage
  libs/remix-tests/tests/testRunner.cli.spec.ts
Labels: autosquash, remix-tests, tests

#720 Debugger react app
  apps/debugger/.babelrc
  apps/debugger/.browserslistrc
  apps/debugger/src/app/app.tsx
  apps/debugger/src/app/debugger.ts
  apps/debugger/src/assets/.gitkeep
  apps/debugger/src/environments/environment.prod.ts
  apps/debugger/src/environments/environment.ts
  apps/debugger/src/favicon.ico
  apps/debugger/src/index.html
  apps/debugger/src/main.tsx
  apps/debugger/src/polyfills.ts
  apps/debugger/src/styles.css
  apps/debugger/tsconfig.app.json
  apps/debugger/tsconfig.json
  apps/debugger/tsconfig.spec.json
  apps/debugger/webpack.config.js
  apps/remix-ide-e2e/src/commands/debugTransaction.ts
  apps/remix-ide-e2e/src/commands/goToVMTraceStep.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/compiler/compiler-sourceVerifier-fetchAndCompile.js
  apps/remix-ide/src/app/components/local-plugin.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/tabs/debugger-tab.js
  apps/remix-ide/src/lib/offsetToLineColumnConverter.js
  libs/remix-debug/src/debugger/debugger.ts
  libs/remix-ui/debugger-ui/src/index.ts
  libs/remix-ui/debugger-ui/src/lib/DebuggerAPI.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-api.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/idebugger-api.ts
  nx.json
  package-lock.json
  package.json
  tslint.json
  workspace.json
Labels: autosquash

#742 Capitalize
  apps/remix-ide/src/app/components/plugin-manager-component.js
Labels: autosquash

#745 Debugger Iframe plugin
  apps/debugger/.babelrc
  apps/debugger/.browserslistrc
  apps/debugger/src/app/app.tsx
  apps/debugger/src/app/debugger-api.ts
  apps/debugger/src/app/debugger.ts
  apps/debugger/src/assets/.gitkeep
  apps/debugger/src/environments/environment.prod.ts
  apps/debugger/src/environments/environment.ts
  apps/debugger/src/favicon.ico
  apps/debugger/src/index.html
  apps/debugger/src/index.ts
  apps/debugger/src/main.tsx
  apps/debugger/src/polyfills.ts
  apps/debugger/src/styles.css
  apps/debugger/tsconfig.app.json
  apps/debugger/tsconfig.json
  apps/debugger/tsconfig.spec.json
  apps/debugger/webpack.config.js
  apps/remix-ide-e2e/src/commands/debugTransaction.ts
  apps/remix-ide-e2e/src/commands/goToVMTraceStep.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/compiler/compiler-sourceVerifier-fetchAndCompile.js
  apps/remix-ide/src/app/components/local-plugin.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/tabs/debugger-tab.js
  apps/remix-ide/src/lib/offsetToLineColumnConverter.js
  libs/remix-debug/src/debugger/debugger.ts
  libs/remix-ui/debugger-ui/src/index.ts
  libs/remix-ui/debugger-ui/src/lib/DebuggerAPI.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/idebugger-api.ts
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  tslint.json
  workspace.json
Labels: autosquash

#714 canActivate option
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash

#753 the file removed event is blocked
  apps/remix-ide/src/app/files/fileManager.js
Labels: autosquash, bug

#741 custom compiler context for remix-tests CLI
  libs/remix-solidity/src/compiler/compiler.ts
  libs/remix-tests/package.json
  libs/remix-tests/src/compiler.ts
  libs/remix-tests/src/run.ts
  libs/remix-tests/src/runTestFiles.ts
  libs/remix-tests/src/types.ts
  libs/remix-tests/tests/testRunner.cli.spec.ts
  libs/remix-tests/tests/testRunner.spec.ts
Labels: autosquash, remix-tests

#725 changed focus methods
  apps/remix-ide/src/app/components/main-panel.js
  apps/remix-ide/src/app/components/side-panel.js
Labels: autosquash

#756 Fixed file explorer bugs
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
Labels: fix, remix-ide

#752 Context Menu For Plugins
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/file-explorer/src/lib/file-explorer-context-menu.tsx
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
Labels: remix-ide

#764 remix-tests readme updated for CLI
  libs/remix-tests/README.md
Labels: documentation, remix-tests

#763 Update fileManager.js
  apps/remix-ide/src/app/files/fileManager.js
Labels: autorebase

#768 fix highlighting
  apps/remix-ide/src/app/editor/SourceHighlighters.js
Labels: autosquash

#760 Create automation.md (PR automation)
  automation.md
Labels: autosquash

#769 Open manually created file
  apps/remix-ide-e2e/src/commands/addFile.ts
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: fix, remix-ide

#782 Fix UnitTest
  libs/remix-url-resolver/tests/test.ts
Labels: autorebase

#783 Fix UnitTest
  libs/remix-url-resolver/tests/test.ts
Labels: autorebase

#788 Fixed Create And Upload File in Home Tab
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
  libs/remix-ui/file-explorer/src/lib/file-explorer-menu.tsx
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
Labels: fix, remix-ide

#790 Fix create and upload file in home tab
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
  libs/remix-ui/file-explorer/src/lib/file-explorer-menu.tsx
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
Labels: fix, remix-ide

#786 fix events
  apps/remix-ide/src/app/files/fileManager.js
Labels: autosquash

#791 check for view in SA plugin
  apps/remix-ide/src/app/tabs/staticanalysis/staticAnalysisView.js
Labels: autorebase

#780 focus on File explorers on deactivate from vertical icons panel
  apps/remix-ide/src/app/components/vertical-icons.js
Labels: autorebase

#805 add warning to reload the page
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide/src/app/tabs/settings-tab.js
Labels: autorebase

#806 fixed the Alignement of caret/triangle and label in array var for
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/dropdown-panel.tsx
Labels: autorebase

#814 Fixed File-Explorer Bugs
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: autorebase, fix, remix-ide
