Repository remix-project-org/remix-project, pull requests merged in 2021-03, with the labels that each got.

#923 Resolver engine is removed
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
  package-lock.json
  package.json
Labels: autorebase

#924 Move workspace to a react component
  apps/remix-ide-e2e/src/commands/removeFile.ts
  apps/remix-ide-e2e/src/tests/fileExplorer.test.ts
  apps/remix-ide-e2e/src/tests/gist.test.ts
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/files/fileManager.js
  apps/remix-ide/src/app/files/remixDProvider.js
  apps/remix-ide/src/app/files/remixd-handle.js
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/panels/styles/file-panel-styles.css
  libs/remix-ui/modal-dialog/src/lib/remix-ui-modal-dialog.tsx
  libs/remix-ui/workspace/.babelrc
  libs/remix-ui/workspace/.eslintrc
  libs/remix-ui/workspace/README.md
  libs/remix-ui/workspace/src/index.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.css
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/tsconfig.json
  libs/remix-ui/workspace/tsconfig.lib.json
  nx.json
  tsconfig.json
  workspace.json
Labels: autorebase, remix-ide

#928 removed invalid example from import github file
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
Labels: autosquash

#931 Update README.md
  libs/remixd/README.md
Labels: autosquash

#934 added alert to update remixd
  apps/remix-ide/src/app/files/remixd-handle.js
Labels: autosquash

#941 update matomo modal
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/tabs/settings-tab.js
Labels: autosquash

#949 Added loader for localhost
  apps/remix-ide/src/app/files/remixDProvider.js
  apps/remix-ide/src/app/files/remixd-handle.js
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: UX, remix-ide

#947 Fix importing file using localhost
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/src/app/compiler/compiler-imports.js
  apps/remix-ide/src/app/files/remixDProvider.js
Labels: autorebase

#966 Refactored Context Menu
  libs/remix-ui/file-explorer/src/lib/file-explorer-context-menu.tsx
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: fix, remix-ide

#970 Fix multiple badges
  apps/remix-ide/src/app/components/vertical-icons.js
Labels: autosquash, fix, remix-ide

#972 Ok to OK in file explorer modals
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: autorebase

#971 Update remixd modal
  apps/remix-ide/src/app/files/remixd-handle.js
Labels: UI, autosquash

#968 Update publish to gist modal with workspace name.
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: autosquash, remix-ide

#974 Add workspace name to tabs
  apps/remix-ide-e2e/src/tests/defaultLayout.test.ts
  apps/remix-ide-e2e/src/tests/gist.test.ts
  apps/remix-ide/src/app/files/fileManager.js
  apps/remix-ide/src/app/panels/tab-proxy.js
Labels: remix-ide

#980 fix switching workspaces
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: bug, remix-ide

#953 Matomo modal update
  apps/remix-ide/src/app.js
Labels: autorebase

#981 Remove carat
  libs/remix-ui/file-explorer/src/lib/file-explorer-menu.tsx
  libs/remix-ui/tree-view/src/lib/tree-view-item/tree-view-item.tsx
Labels: remix-ide

#979 updated the remix-tabs version
  package-lock.json
  package.json
Labels: autorebase

#982 Fix create gist
  apps/remix-ide/src/app/files/fileProvider.js
  apps/remix-ide/src/app/files/workspaceFileProvider.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: autorebase

#984 Fix switch workspace when remixd is activated from the plugin manager
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remixd/src/bin/remixd.ts
Labels: bug, remix-ide

#986 Display localhost title after connection to remixd
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: UX

#993 bugfix app manager
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash, bug

#1009 Fix Matomo
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/tabs/settings-tab.js
Labels: autosquash

#1018 check for whitespaces in foldername
  apps/remix-ide/src/app/tabs/testTab/testTab.js
Labels: autorebase

#998 Update release-process.md
  release-process.md
Labels: autorebase

#1020 enable matomo for live
  apps/remix-ide/src/app.js
  apps/remix-ide/src/index.html
Labels: autorebase

#1026 migration modal improvements
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
Labels: autorebase

#1019 Delete yarn.lock
  yarn.lock
Labels: autorebase

#1023 Keep gist in a separate workspace at load
  apps/remix-ide/src/app/panels/file-panel.js
Labels: autosquash

#1045 Fixed allowed methods
  libs/remixd/src/services/gitClient.ts
  libs/remixd/src/services/remixdClient.ts
Labels: autosquash, bug

#1053 Make readonly immutable
  libs/remixd/src/bin/remixd.ts
  libs/remixd/src/services/gitClient.ts
  libs/remixd/src/services/remixdClient.ts
Labels: remixD

#1047 Disable git
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide/src/app/files/remixd-handle.js
  apps/remix-ide/src/app/panels/terminal.js
  libs/remixd/src/bin/remixd.ts
Labels: autosquash

#1052 Restrict file operations to workspace / shared folder.
  apps/remix-ide/src/app/files/workspaceFileProvider.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remixd/src/utils.ts
  package.json
Labels: autorebase, enhancement, remix-ide, remixD

#1057 Bump remixd version
  libs/remixd/package.json
Labels: remixD
