Repository remix-project-org/remix-project, pull requests merged in 2021-09, with the labels that each got.

#1573 removing event listener fixed
  apps/remix-ide/src/app/tabs/test-tab.js
Labels: Solidity Unit Testing Plugin

#1578 hardhat compilation with error and result fixed
  libs/remixd/src/services/hardhatClient.ts
Labels: remixD, hardhat

#1542 fix gasUsed in the receipt
  libs/remix-lib/src/web3Provider/web3VmProvider.ts
  libs/remix-simulator/src/methods/transactions.ts
Labels: autosquash

#1580 fix whitespaces and canactivate
  libs/remix-ui/plugin-manager/src/lib/components/LocalPluginForm.tsx
  libs/remix-ui/plugin-manager/src/types.d.ts
Labels: bug

#1583 set current file when compiler is being called through the API.
  apps/solidity-compiler/src/app/compiler-api.ts
Labels: autosquash

#1591 Fix e2e locally
  apps/remix-ide-e2e/src/tests/solidityUnittests.spec.ts
Labels: autosquash

#1602 Test local plugin canActivate
  .circleci/config.yml
  apps/remix-ide-e2e/nightwatch.ts
  apps/remix-ide-e2e/src/local-plugin/.babelrc
  apps/remix-ide-e2e/src/local-plugin/.browserslistrc
  apps/remix-ide-e2e/src/local-plugin/.eslintrc
  apps/remix-ide-e2e/src/local-plugin/src/app/app.css
  apps/remix-ide-e2e/src/local-plugin/src/app/app.tsx
  apps/remix-ide-e2e/src/local-plugin/src/app/logo.svg
  apps/remix-ide-e2e/src/local-plugin/src/app/star.svg
  apps/remix-ide-e2e/src/local-plugin/src/assets/.gitkeep
  apps/remix-ide-e2e/src/local-plugin/src/environments/environment.prod.ts
  apps/remix-ide-e2e/src/local-plugin/src/environments/environment.ts
  apps/remix-ide-e2e/src/local-plugin/src/favicon.ico
  apps/remix-ide-e2e/src/local-plugin/src/index.html
  apps/remix-ide-e2e/src/local-plugin/src/main.tsx
  apps/remix-ide-e2e/src/local-plugin/src/polyfills.ts
  apps/remix-ide-e2e/src/local-plugin/src/styles.css
  apps/remix-ide-e2e/src/local-plugin/tsconfig.app.json
  apps/remix-ide-e2e/src/local-plugin/tsconfig.json
  apps/remix-ide-e2e/src/tests/pluginManager.ts
  apps/remix-ide/ci/browser_tests_plugin_manager.sh
  nx.json
  package.json
  workspace.json
Labels: browser-tests
