Repository remix-project-org/remix-project, pull requests merged in 2021-06, with the labels that each got.

#1250 cleanup workspaces useEffect after unmount
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix

#1257 Queue file operation events
  apps/remix-ide-e2e/src/helpers/init.ts
  apps/remix-ide-e2e/src/tests/gist.spec.ts
  apps/remix-ide-e2e/src/tests/url.spec.ts
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/file-explorer/src/lib/actions/fileSystem.ts
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: fix

#1261 Fix decoding struct
  libs/remix-debug/src/solidity-decoder/astHelper.ts
  libs/remix-debug/src/solidity-decoder/decodeInfo.ts
Labels: fix

#1262 remixd modal content updated
  apps/remix-ide/src/app/files/remixd-handle.js
Labels: remix-ide, remixD

#1271 use bignumber, previously in pullrequest #1174
  libs/remix-lib/src/execution/txRunnerVM.ts
Labels: fix

#1299 fix switch to code-sample workspace
  apps/remix-ide-e2e/src/commands/currentWorkspaceIs.ts
  apps/remix-ide-e2e/src/tests/url.spec.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix

#1208 Fork selection for javascript VM
  apps/debugger/src/app/debugger-api.ts
  apps/remix-ide-e2e/src/tests/recorder.spec.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.spec.ts
  apps/remix-ide/src/app/tabs/runTab/settings.js
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/blockchain/providers/vm.js
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-debug/src/Ethdebugger.ts
  libs/remix-debug/src/code/codeManager.ts
  libs/remix-debug/src/code/codeResolver.ts
  libs/remix-debug/src/code/codeUtils.ts
  libs/remix-debug/src/debugger/debugger.ts
  libs/remix-debug/src/trace/traceManager.ts
  libs/remix-lib/package.json
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-simulator/package.json
  libs/remix-simulator/src/provider.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-simulator/test/accounts.ts
  libs/remix-simulator/test/blocks.ts
  libs/remix-simulator/test/misc.ts
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  package-lock.json
  package.json
Labels: remix-ide

#1313 timestamp added for VM only
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-lib/src/execution/txRunnerWeb3.ts
Labels: bugfix

#1314 tslib added as a dependency
  libs/remix-tests/package.json
  package-lock.json
  package.json
Labels: remix-tests

#1327 Stop publish to gist e2e
  apps/remix-ide-e2e/src/tests/fileExplorer.test.ts
  apps/remix-ide-e2e/src/tests/gist.spec.ts
Labels: autosquash, browser-tests

#1308 ignore mapping if struct in memory
  libs/remix-debug/src/solidity-decoder/types/Mapping.ts
  libs/remix-debug/src/solidity-decoder/types/Struct.ts
Labels: autosquash, fix

#1304 e2e for testing large value
  apps/remix-ide-e2e/src/tests/specialFunctions.test.ts
Labels: autosquash

#1265 fix logger bug
  apps/remix-ide/src/app/ui/txLogger.js
Labels: autorebase

#1263 short flags for remixd options added
  libs/remixd/README.md
  libs/remixd/src/bin/remixd.ts
Labels: autorebase, remixD

#1330 update to Settings JavaScript VM
  apps/remix-ide/src/app/tabs/settings-tab.js
Labels: autosquash

#1171 feat: task configuration and creating of setting-tab in react
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.ts
  apps/remix-ide/src/app/tabs/settings-tab.js
  libs/remix-ui/clipboard/src/lib/copy-to-clipboard/copy-to-clipboard.tsx
  libs/remix-ui/settings/.babelrc
  libs/remix-ui/settings/.eslintrc
  libs/remix-ui/settings/README.md
  libs/remix-ui/settings/src/index.ts
  libs/remix-ui/settings/src/lib/constants.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.css
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
  libs/remix-ui/settings/src/lib/settingsReducer.ts
  libs/remix-ui/settings/tsconfig.json
  libs/remix-ui/settings/tsconfig.lib.json
  nx.json
  package.json
  tsconfig.json
  workspace.json
Labels: autorebase, autosquash, ready

#1340 Make sure current fork is set before continuing
  apps/remix-ide/src/blockchain/execution-context.js
Labels: autosquash
