Repository remix-project-org/remix-project, pull requests merged in 2021-07, with the labels that each got.

#1346 fixing editor issue
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
Labels: fix

#1182 added customactions
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/file-explorer/src/lib/file-explorer-context-menu.tsx
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  package.json
Labels: autorebase

#1281 tracking compiler version
  apps/remix-ide/src/app/tabs/compileTab/compilerContainer.js
Labels: autorebase

#1350 fix debugger crash
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/solidity-state.tsx
  libs/remix-ui/debugger-ui/src/utils/solidityTypeFormatter.ts
Labels: bug

#1353 Fixed settings tab
  apps/remix-ide-e2e/src/tests/editor.spec.ts
  apps/remix-ide/src/app/tabs/settings-tab.js
  libs/remix-ui/settings/src/lib/constants.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
Labels: bugfix

#1356 Add solidity compile custom action
  apps/remix-ide/src/app/tabs/compile-tab.js
Labels: autosquash

#1374 imports location fixed for static analysis
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: Static Analysis Plugin, bugfix

#1384 Fix matomo event
  apps/remix-ide/src/app/tabs/compileTab/compilerContainer.js
Labels: autorebase

#1339 React compiler
  apps/remix-ide-e2e/src/commands/getModalBody.ts
  apps/remix-ide-e2e/src/commands/verifyContracts.ts
  apps/remix-ide-e2e/src/tests/publishContract.test.ts
  apps/remix-ide-e2e/src/tests/url.spec.ts
  apps/remix-ide-e2e/src/tests/usingWebWorker.test.ts
  apps/remix-ide/src/app/tabs/compile-tab.js
  apps/remix-ide/src/app/ui/copy-to-clipboard.js
  libs/remix-ui/clipboard/src/lib/copy-to-clipboard/copy-to-clipboard.tsx
  libs/remix-ui/modal-dialog/src/lib/types/index.ts
  libs/remix-ui/publish-to-storage/.babelrc
  libs/remix-ui/publish-to-storage/.eslintrc
  libs/remix-ui/publish-to-storage/README.md
  libs/remix-ui/publish-to-storage/src/index.ts
  libs/remix-ui/publish-to-storage/src/lib/publish-to-storage.css
  libs/remix-ui/publish-to-storage/src/lib/publish-to-storage.tsx
  libs/remix-ui/publish-to-storage/src/lib/publishOnSwarm.tsx
  libs/remix-ui/publish-to-storage/src/lib/publishToIPFS.tsx
  libs/remix-ui/publish-to-storage/src/lib/types/index.ts
  libs/remix-ui/publish-to-storage/tsconfig.json
  libs/remix-ui/publish-to-storage/tsconfig.lib.json
  libs/remix-ui/renderer/.babelrc
  libs/remix-ui/renderer/.eslintrc
  libs/remix-ui/renderer/README.md
  libs/remix-ui/renderer/src/index.ts
  libs/remix-ui/renderer/src/lib/renderer.css
  libs/remix-ui/renderer/src/lib/renderer.tsx
  libs/remix-ui/renderer/tsconfig.json
  libs/remix-ui/renderer/tsconfig.lib.json
  libs/remix-ui/solidity-compiler/.babelrc
  libs/remix-ui/solidity-compiler/.eslintrc
  libs/remix-ui/solidity-compiler/README.md
  libs/remix-ui/solidity-compiler/src/index.ts
  libs/remix-ui/solidity-compiler/src/lib/actions/compiler.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
  libs/remix-ui/solidity-compiler/src/lib/css/style.css
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/compiler-abstract.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/compiler-helpers.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/compiler-utils.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/contract-parser.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/index.ts
  libs/remix-ui/solidity-compiler/src/lib/reducers/compiler.ts
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
  libs/remix-ui/solidity-compiler/src/lib/types/index.ts
  libs/remix-ui/solidity-compiler/tsconfig.json
  libs/remix-ui/solidity-compiler/tsconfig.lib.json
  nx.json
  package-lock.json
  package.json
  tsconfig.json
  workspace.json
Labels: remix-ide

#1394 reset static analysis plugin on workspace change
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: Static Analysis Plugin

#1411 hide slither button when not localhost workspace
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: Static Analysis Plugin
