Repository remix-project-org/remix-project, pull requests merged in 2021-02, with the labels that each got.

#822 Fix decoding data of PUSH
  libs/remix-debug/src/code/codeUtils.ts
Labels: autosquash

#825 example readme updated
  apps/remix-ide/src/app/editor/examples.js
Labels: autorebase, documentation

#824 correct example for import with url
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
Labels: autorebase

#819 Remove walletconnect, dgit and update script runner
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash

#827 Bump remixd version and fixed file creation error for localhost
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remixd/package.json
Labels: fix, remix-ide

#776 Update release-process.md
  release-process.md
Labels: autorebase, autosquash

#835 Root readme
  README.md
  apps/remix-ide/remix_screenshot.png
Labels: autorebase

#837 current folder changed
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/files/remixDProvider.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remixd/src/index.ts
  libs/remixd/src/services/remixdClient.ts
Labels: bug, fix

#847 Fix e2e test
  apps/remix-ide-e2e/src/tests/debugger.test.ts
Labels: browser-tests, fix

#848 handle other kind of contract file
  apps/remix-ide/src/app/tabs/runTab/contractDropdown.js
Labels: autorebase

#854 pragma updated to support 0.8
  libs/remix-tests/sol/tests.sol.ts
  libs/remix-tests/sol/tests_accounts.sol.ts
Labels: autorebase, remix-tests

#856 Load base64 encoded code
  apps/remix-ide-e2e/src/tests/url.test.ts
  apps/remix-ide/src/app.js
Labels: autosquash

#863 Add negative test for publish to gist with missing gist token.
  apps/remix-ide-e2e/src/tests/gist.test.ts
  nodemon.json
  package.json
Labels: autorebase, browser-tests

#867 Jump Out Trigger Enabled
  libs/remix-debug/src/debugger/stepManager.ts
  libs/remix-ui/debugger-ui/src/lib/button-navigator/button-navigator.tsx
Labels: remix-ide

#876 Improve annotations
  apps/remix-ide-e2e/src/commands/checkAnnotations.ts
  apps/remix-ide-e2e/src/commands/checkAnnotationsNotPresent.ts
  apps/remix-ide-e2e/src/tests/editor.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/tabs/compile-tab.js
  apps/remix-ide/src/app/tabs/compileTab/compileTab.js
  apps/remix-ide/src/app/tabs/staticanalysis/staticAnalysisView.js
  apps/remix-ide/src/app/tabs/test-tab.js
  apps/remix-ide/src/app/ui/renderer.js
Labels: autosquash

#864 Set account & env
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/tabs/runTab/settings.js
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/pluginUDapp.js
Labels: autosquash

#888 allow spaces in names, duplicate tabs opened
  apps/remix-ide/src/app/panels/tab-proxy.js
Labels: autosquash, bug

#904 Fix saving of empty content
  apps/remix-ide/src/app/files/fileManager.js
Labels: fix, remix-ide

#892 Select files on hover and context menu display
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
  libs/remix-ui/file-explorer/src/lib/types/index.ts
  libs/remix-ui/tree-view/src/types/index.ts
Labels: autorebase, remix-ide

#893 Rntabs
  apps/remix-ide/src/app/files/fileManager.js
  apps/remix-ide/src/app/panels/tab-proxy.js
Labels: autosquash

#906 Display icons based on file types.
  apps/remix-ide-e2e/src/commands/testFunction.ts
  apps/remix-ide/src/index.html
  apps/remix-ide/src/lib/helper.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: enhancement, remix-ide

#903 Don't display dependent modules in the plugin manager
  apps/remix-ide/src/app/components/plugin-manager-component.js
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash

#913 Display icons for open file tabs
  apps/remix-ide/src/app/panels/tab-proxy.js
  package-lock.json
  package.json
Labels: autorebase, enhancement, remix-ide

#911 added track of theme changes
  apps/remix-ide/src/app/tabs/theme-module.js
Labels: autorebase

#914 message for users of < 0.4.12 version
  apps/remix-ide/src/app/tabs/compileTab/compilerContainer.js
Labels: autorebase

#918 fixed saving matomo choice in localstorage
  apps/remix-ide/src/app/tabs/settings-tab.js
Labels: autorebase

#919 added matomo for remix and remix-beta
  apps/remix-ide/src/index.html
Labels: autorebase

#891 default solidity compiler version set to 0.8.1
  apps/remix-ide-e2e/src/examples/example-contracts.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/fileManager_api.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.ts
  apps/remix-ide-e2e/src/tests/signingMessage.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  apps/remix-ide/ci/makeMockCompiler.js
  apps/remix-ide/src/app/editor/examples.js
  apps/remix-ide/src/app/tabs/compileTab/compilerContainer.js
  apps/remix-ide/src/app/tabs/testTab/testTab.js
  package.json
Labels: autorebase, remix-ide, solidity compiler plugin

#921 filtered out serveice plugins
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash
