Repository remix-project-org/remix-project, pull requests merged in 2021-04, with the labels that each got.

#1061 catch errors for exposed methods
  apps/remix-ide/src/app/files/fileManager.js
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: remix-ide

#1063 adding error tracking
  apps/remix-ide/src/index.html
Labels: autorebase

#1062 Update remix-plugin version to 0.3.11-alpha.5
  package-lock.json
  package.json
Labels: remix-ide

#1066 add method
  libs/remixd/src/services/remixdClient.ts
Labels: autorebase

#1070 bump remixd version
  libs/remixd/package.json
  package-lock.json
Labels: remixD

#1073 fix FE not rendering and display alert
  apps/remix-ide/src/app/panels/file-panel.js
Labels: autosquash

#1093 return after reject
  libs/remixd/src/services/remixdClient.ts
Labels: autosquash, remixD

#1036 Typo Zip file
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
Labels: autorebase

#1041 Optimise e2e
  .circleci/config.yml
  apps/remix-ide-e2e/src/commands/addFile.ts
  apps/remix-ide-e2e/src/commands/checkVariableDebug.ts
  apps/remix-ide-e2e/src/commands/clickInstance.ts
  apps/remix-ide-e2e/src/commands/goToVMTraceStep.ts
  apps/remix-ide-e2e/src/commands/noWorkerErrorFor.ts
  apps/remix-ide-e2e/src/commands/openFile.ts
  apps/remix-ide-e2e/src/commands/verifyContracts.ts
  apps/remix-ide-e2e/src/commands/waitForElementContainsText.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.spec.ts
  apps/remix-ide-e2e/src/tests/compiler_api.test.ts
  apps/remix-ide-e2e/src/tests/debugger.spec.ts
  apps/remix-ide-e2e/src/tests/defaultLayout.test.ts
  apps/remix-ide-e2e/src/tests/editor.spec.ts
  apps/remix-ide-e2e/src/tests/fileExplorer.test.ts
  apps/remix-ide-e2e/src/tests/fileManager_api.spec.ts
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide-e2e/src/tests/gist.spec.ts
  apps/remix-ide-e2e/src/tests/libraryDeployment.test.ts
  apps/remix-ide-e2e/src/tests/pluginManager.spec.ts
  apps/remix-ide-e2e/src/tests/publishContract.test.ts
  apps/remix-ide-e2e/src/tests/recorder.spec.ts
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.ts
  apps/remix-ide-e2e/src/tests/signingMessage.test.ts
  apps/remix-ide-e2e/src/tests/solidityImport.spec.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.spec.ts
  apps/remix-ide-e2e/src/tests/specialFunctions.test.ts
  apps/remix-ide-e2e/src/tests/staticAnalysis.spec.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.spec.ts
  apps/remix-ide-e2e/src/tests/txListener.test.ts
  apps/remix-ide-e2e/src/tests/url.spec.ts
  apps/remix-ide-e2e/src/tests/usingWebWorker.test.ts
  apps/remix-ide-e2e/src/tests/verticalIconsPanel.spec.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/ci/browser_tests_chrome_1.sh
  apps/remix-ide/ci/browser_tests_chrome_2.sh
  apps/remix-ide/ci/browser_tests_firefox_1.sh
  apps/remix-ide/ci/browser_tests_firefox_2.sh
  apps/remix-ide/src/app/ui/renderer.js
  package.json
Labels: browser-tests, ready

#1106 e2e and remix-lib test in parallel
  .circleci/config.yml
Labels: autosquash

#1105 Close all tabs when workspace changes
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/files/fileManager.js
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/panels/tab-proxy.js
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: autosquash

#1072 alert user when full while migrating
  apps/remix-ide/src/migrateFileSystem.js
Labels: autosquash

#1115 Update label migration failed
  apps/remix-ide/src/migrateFileSystem.js
Labels: autosquash

#1113 Fix upload file on sub folder
  libs/remix-ui/file-explorer/src/lib/file-explorer.tsx
Labels: autosquash

#1114 attempt fixing GoToVmTraceStep
  .circleci/config.yml
  apps/remix-ide-e2e/src/commands/debugTransaction.ts
  apps/remix-ide-e2e/src/commands/goToVMTraceStep.ts
  apps/remix-ide-e2e/src/commands/testFunction.ts
Labels: autorebase, browser-tests

#1120 Bump remixd version
  libs/remixd/package.json
Labels: remixD

#1109 generated test file updated
  apps/remix-ide/src/app/tabs/testTab/testTab.js
Labels: Solidity Unit Testing Plugin

#1142 use ethers.js 5.1.4
  apps/remix-ide-e2e/src/tests/recorder.spec.ts
  package-lock.json
  package.json
Labels: autosquash

#1110 Fixmanagerdeact
  apps/remix-ide/src/app/components/plugin-manager-component.js
  apps/remix-ide/src/app/panels/tab-proxy.js
  apps/remix-ide/src/remixAppManager.js
Labels: autorebase

#1149 show message if debugging on kovan
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
Labels: autosquash

#1148 better url scheme
  apps/remix-ide-e2e/src/tests/publishContract.test.ts
  apps/remix-ide/src/publishToStorage.js
Labels: autosquash

#978 Use workspace provider for setting up the files
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: autosquash

#1150 rename fileExplorers to filePanel
  apps/remix-ide-e2e/src/commands/addFile.ts
  apps/remix-ide-e2e/src/commands/openFile.ts
  apps/remix-ide-e2e/src/helpers/init.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.spec.ts
  apps/remix-ide-e2e/src/tests/debugger.spec.ts
  apps/remix-ide-e2e/src/tests/defaultLayout.test.ts
  apps/remix-ide-e2e/src/tests/editor.spec.ts
  apps/remix-ide-e2e/src/tests/fileExplorer.test.ts
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide-e2e/src/tests/gist.spec.ts
  apps/remix-ide-e2e/src/tests/publishContract.test.ts
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.ts
  apps/remix-ide-e2e/src/tests/solidityImport.spec.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.spec.ts
  apps/remix-ide-e2e/src/tests/usingWebWorker.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/components/vertical-icons.js
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/ui/landing-page/landing-page.js
  apps/remix-ide/src/framingService.js
  apps/remix-ide/src/remixAppManager.js
Labels: autosquash
