Repository remix-project-org/remix-project, pull requests merged in 2022-12, with the labels that each got.

#3048 add "create sol github action" to the FE menu
  apps/remix-ide/src/app/tabs/locales/en-US.js
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/css/remix-ui-workspace.css
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#3197 Fix unique key error in button navigation
  libs/remix-ui/debugger-ui/src/lib/button-navigator/button-navigator.tsx
Labels: ready-to-review

#3187 Save proxy addresses and storage layout for upgrade. (Secure Upgrade Part1)
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-core-plugin/src/lib/openzeppelin-proxy.ts
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: ready-for-review

#3201 Add Solidity Survey to Feature Section
  apps/remix-ide/src/app/tabs/locales/en/home.json
  apps/remix-ide/src/app/tabs/locales/zh/home.json
  apps/remix-ide/src/assets/img/solidity-logo.webp
  libs/remix-ui/home-tab/src/lib/components/homeTabFeatured.tsx
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.css
Labels: ready-for-review

#3215 Remove redundant caret tooltip
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: ready-for-review

#3209 Make SolidityProxy to dyn resolve compilation result
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-debug/src/Ethdebugger.ts
  libs/remix-debug/src/code/breakpointManager.ts
  libs/remix-debug/src/debugger/solidityState.ts
  libs/remix-debug/src/debugger/stepManager.ts
  libs/remix-debug/src/solidity-decoder/internalCallTree.ts
  libs/remix-debug/src/solidity-decoder/solidityProxy.ts
  libs/remix-debug/test/debugger.ts
  libs/remix-debug/test/decoder/localDecoder.ts
  libs/remix-debug/test/decoder/localsTests/calldata.ts
  libs/remix-debug/test/decoder/localsTests/int.ts
  libs/remix-debug/test/decoder/localsTests/misc.ts
  libs/remix-debug/test/decoder/localsTests/misc2.ts
  libs/remix-debug/test/decoder/localsTests/structArray.ts
  libs/remix-debug/test/decoder/stateTests/mapping.ts
  libs/remix-debug/test/decoder/storageDecoder.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/slider/slider.tsx
  libs/remix-ui/debugger-ui/src/lib/step-manager/step-manager.tsx
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: ready-to-review

#3213 add mp3
  apps/remix-ide/src/assets/audio/remiGuitar-single-power-chord-A-minor.mp3
  libs/remix-ui/home-tab/src/lib/components/homeTabTitle.tsx
Labels: performance, bugfix

#3224 Lengthy Compile Button Text Fix
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: fix, ready-for-review

#3225 Remove Custom css styling
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: fix, ready-for-review

#3234 shows revert reason for the test
  libs/remix-tests/src/testRunner.ts
Labels: ready-to-review
