Repository remix-project-org/remix-project, pull requests merged in 2022-06, with the labels that each got.

#2462 do not compile if not sol files & fix typescript autocompletion
  apps/remix-ide/src/app/editor/editor.js
  apps/solidity-compiler/src/app/compiler-api.ts
Labels: publish

#2477 bug fixes
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/search/src/lib/context/context.tsx
Labels: publish

#2470 added Berlin, fixed config file logic
  apps/remix-ide-e2e/src/commands/verifyContracts.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/compiler_api.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/tabs/compile-tab.js
  apps/solidity-compiler/src/app/compiler-api.ts
  libs/remix-lib/src/types/ICompilerApi.ts
  libs/remix-ui/editor/src/lib/remix-plugin-types.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
  libs/remix-ui/solidity-compiler/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/css/remix-ui-workspace.css
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  package.json
Labels: publish

#2471 update remixd modal text
  apps/remix-ide/src/app/plugins/remixd-handle.tsx
Labels: autorebase, publish

#2482 RSS
  libs/remix-ui/home-tab/src/lib/components/rssFeed.css
  libs/remix-ui/home-tab/src/lib/components/rssFeed.tsx
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  package.json
Labels: autorebase, publish

#2494 Fix height in File-Explorer
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix

#2490 fix typescript error
  apps/remix-ide-e2e/src/tests/search.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  libs/remix-ui/editor/src/lib/web-types.ts
  libs/remix-ws-templates/src/templates/ozerc20/scripts/ethers-lib.ts
  libs/remix-ws-templates/src/templates/ozerc20/scripts/web3-lib.ts
  libs/remix-ws-templates/src/templates/ozerc721/scripts/ethers-lib.ts
  libs/remix-ws-templates/src/templates/ozerc721/scripts/web3-lib.ts
  libs/remix-ws-templates/src/templates/remixDefault/scripts/ethers-lib.ts
  libs/remix-ws-templates/src/templates/remixDefault/scripts/web3-lib.ts
  libs/remix-ws-templates/src/templates/zeroxErc20/scripts/ethers-lib.ts
  libs/remix-ws-templates/src/templates/zeroxErc20/scripts/web3-lib.ts
Labels: publish

#2260 Support Proxy
  .eslintrc.json
  apps/remix-ide-e2e/src/commands/createContract.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/libraryDeployment.test.ts
  apps/remix-ide-e2e/src/tests/recorder.test.ts
  apps/remix-ide-e2e/src/tests/signingMessage.test.ts
  apps/remix-ide-e2e/src/tests/specialFunctions.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-core-plugin/src/lib/constants/uups.ts
  libs/remix-core-plugin/src/lib/openzeppelin-proxy.ts
  libs/remix-core-plugin/src/types/contract.ts
  libs/remix-lib/src/execution/txFormat.ts
  libs/remix-lib/test/txFormat.ts
  libs/remix-ui/helper/src/lib/helper-components.tsx
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/actions.ts
  libs/remix-ui/run-tab/src/lib/actions/deploy.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/actions/payload.ts
  libs/remix-ui/run-tab/src/lib/actions/recorder.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/deployButton.tsx
  libs/remix-ui/run-tab/src/lib/components/deployInput.tsx
  libs/remix-ui/run-tab/src/lib/components/instanceContainerUI.tsx
  libs/remix-ui/run-tab/src/lib/components/mainnet.tsx
  libs/remix-ui/run-tab/src/lib/components/multiDeployInput.tsx
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
  libs/remix-ui/run-tab/src/lib/constants/index.ts
  libs/remix-ui/run-tab/src/lib/css/run-tab.css
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  package-lock.json
  package.json
Labels: WIP, publish

#2574 change all instances of File Explorers to File Explorer
  apps/remix-ide-e2e/src/tests/defaultLayout.test.ts
  apps/remix-ide-e2e/src/tests/fileExplorer.test.ts
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/walkthroughService.js
Labels: UI
