Repository remix-project-org/remix-project, pull requests merged in 2022-08, with the labels that each got.

#2700 flaky test search
  apps/remix-ide-e2e/src/tests/search.test.ts
Labels: autorebase

#2703 show contract from compiled file selected in dropdowns
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
  libs/remix-ui/solidity-compiler/src/lib/types/index.ts
Labels: solidity compiler plugin, UDapp plugin, ready-to-review

#2697 added zoomin and zoomout to context menu of editor
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: autorebase

#2698 new placeholder for solidity path input
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: autorebase

#2741 update security message
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: UX

#2734 Exit process if error is found
  libs/remix-tests/src/run.ts
Labels: fix

#2722 ZoKrates syntax highlighting for the Monaco Editor
  libs/remix-ui/editor/src/lib/cairoSyntax.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/editor/src/lib/syntaxes/cairo.ts
  libs/remix-ui/editor/src/lib/syntaxes/solidity.ts
  libs/remix-ui/editor/src/lib/syntaxes/zokrates.ts
Labels: autorebase

#2743 remix-beta: fix metamask loading and notification
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/global-variables.tsx
  package.json
  yarn.lock
Labels: remix-beta

#2710 add action to copy parameters
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/multiDeployInput.tsx
  libs/remix-ui/run-tab/src/lib/css/run-tab.css
Labels: autorebase, publish

#2668 Filedecoratorplugin
  apps/remix-ide-e2e/src/tests/file_decorator.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/panels/tab-proxy.js
  apps/remix-ide/src/app/plugins/file-decorator.ts
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/file-decorators/.babelrc
  libs/remix-ui/file-decorators/.eslintrc
  libs/remix-ui/file-decorators/src/index.ts
  libs/remix-ui/file-decorators/src/lib/components/file-decoration-icon.tsx
  libs/remix-ui/file-decorators/src/lib/components/filedecorationicons/file-decoration-custom-icon.tsx
  libs/remix-ui/file-decorators/src/lib/components/filedecorationicons/file-decoration-error-icon.tsx
  libs/remix-ui/file-decorators/src/lib/components/filedecorationicons/file-decoration-tooltip.tsx
  libs/remix-ui/file-decorators/src/lib/components/filedecorationicons/file-decoration-warning-icon.tsx
  libs/remix-ui/file-decorators/src/lib/helper/index.tsx
  libs/remix-ui/file-decorators/src/lib/types/index.ts
  libs/remix-ui/file-decorators/tsconfig.json
  libs/remix-ui/file-decorators/tsconfig.lib.json
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
  libs/remix-ui/workspace/src/index.ts
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/payload.ts
  libs/remix-ui/workspace/src/lib/components/file-explorer.tsx
  libs/remix-ui/workspace/src/lib/components/file-label.tsx
  libs/remix-ui/workspace/src/lib/components/file-render.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  nx.json
  tsconfig.base.json
  workspace.json
Labels: ready-to-review

#2744 Fix logging to the terminal & Update Security Message
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
Labels: remix-beta

#2752 fix ipfs publish
  apps/etherscan/src/app/routes.tsx
Labels: etherscan

#2715 update README nx install command
  README.md
Labels: autorebase

#2756 Dropdown Bleed Fix
  apps/remix-ide/src/assets/css/themes/bootstrap-cerulean.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
Labels: ready-for-review

#2747 Spacelabs theme fix
  apps/remix-ide-e2e/src/tests/gist.test.ts
  apps/remix-ide/src/assets/css/themes/bootstrap-spacelab.min.css
Labels: bugfix, ready-to-review

#2774 editor autocomplete/hover/references
  apps/remix-ide-e2e/src/commands/checkTerminalFilter.ts
  apps/remix-ide-e2e/src/examples/editor-test-contracts.ts
  apps/remix-ide-e2e/src/tests/editor.test.ts
  apps/remix-ide-e2e/src/tests/editorAutoComplete.test.ts
  apps/remix-ide-e2e/src/tests/editorHoverContext.test.ts
  apps/remix-ide-e2e/src/tests/editorReferences.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/plugins/parser/code-parser.tsx
  apps/remix-ide/src/app/plugins/parser/services/code-parser-antlr-service.ts
  apps/remix-ide/src/app/plugins/parser/services/code-parser-compiler.ts
  apps/remix-ide/src/app/plugins/parser/services/code-parser-gas-service.ts
  apps/remix-ide/src/app/plugins/parser/types/antlr-types.ts
  apps/remix-ide/src/app/plugins/parser/types/index.ts
  apps/remix-ide/src/assets/js/parser/Solidity-EZVQ6AE4.tokens
  apps/remix-ide/src/assets/js/parser/antlr.js
  apps/remix-ide/src/assets/js/parser/antlr.js.map
  apps/remix-ide/src/index.html
  apps/solidity-compiler/src/app/compiler-api.ts
  apps/solidity-compiler/src/app/compiler.ts
  libs/remix-analyzer/src/types.ts
  libs/remix-core-plugin/src/index.ts
  libs/remix-core-plugin/src/lib/editor-context-listener.ts
  libs/remix-core-plugin/tsconfig.lib.json
  libs/remix-solidity/src/compiler/compiler-worker.ts
  libs/remix-solidity/src/compiler/compiler.ts
  libs/remix-solidity/src/compiler/types.ts
  libs/remix-ui/editor-context-view/.babelrc
  libs/remix-ui/editor-context-view/.eslintrc
  libs/remix-ui/editor-context-view/README.md
  libs/remix-ui/editor-context-view/src/index.ts
  libs/remix-ui/editor-context-view/src/lib/remix-ui-editor-context-view.css
  libs/remix-ui/editor-context-view/src/lib/remix-ui-editor-context-view.tsx
  libs/remix-ui/editor-context-view/tsconfig.json
  libs/remix-ui/editor-context-view/tsconfig.lib.json
  libs/remix-ui/editor/src/lib/actions/editor.ts
  libs/remix-ui/editor/src/lib/providers/completion/completionGlobals.ts
  libs/remix-ui/editor/src/lib/providers/completionProvider.ts
  libs/remix-ui/editor/src/lib/providers/definitionProvider.ts
  libs/remix-ui/editor/src/lib/providers/highlightProvider.ts
  libs/remix-ui/editor/src/lib/providers/hoverProvider.ts
  libs/remix-ui/editor/src/lib/providers/referenceProvider.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/editor/src/lib/web-types.ts
  libs/remix-ui/editor/src/types/monaco.ts
  libs/remix-ui/editor/tsconfig.lib.json
  libs/remix-ui/search/src/lib/context/context.tsx
  libs/remix-ui/settings/src/lib/constants.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
  libs/remix-ui/settings/src/lib/settingsReducer.ts
  nx.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: autosquash

#2781 Grid debugger 2
  apps/debugger/src/app/debugger-api.ts
  apps/debugger/src/app/debugger.ts
  apps/remix-ide-e2e/src/commands/goToVMTraceStep.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide/src/app/components/side-panel.tsx
  apps/remix-ide/src/app/panels/layout.ts
  libs/remix-debug/src/debugger/stepManager.ts
  libs/remix-ui/app/src/lib/remix-app/components/dragbar/dragbar.tsx
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/app/src/lib/remix-app/style/remix-app.css
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/idebugger-api.ts
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/assembly-items.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/calldata-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/callstack-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/code-list-view.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/dropdown-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/full-storages-changes.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/function-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/global-variables.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/memory-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/solidity-locals.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/solidity-state.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/stack-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/step-detail.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/storage-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/vm-debugger-head.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/vm-debugger.tsx
  libs/remix-ui/debugger-ui/src/types/index.ts
Labels: debugger

#2765 Styling Issues with reserved keywords bug in black theme
  apps/remix-ide/src/assets/css/themes/remix-black_undtds.css
Labels: bugfix, ready-to-review

#1527 feat: Theme Hacker Owl
  apps/remix-ide/src/app/tabs/theme-module.js
  apps/remix-ide/src/assets/css/themes/remix-hacker_owl.css
Labels: publish, effort: 2

#2811 add timestamp to url
  apps/remix-ide/src/app/plugins/parser/code-parser.tsx
Labels: bugfix

#2820 fixes FE layout on localhost workspace
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review
