Repository remix-project-org/remix-project, pull requests merged in 2022-02, with the labels that each got.

#2023 Fix copy the deploy payload to clipboard
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: bug, publish

#2027 Remove border for correct cursor position
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: publish

#2038 Reset selected account when account changes on injectedWeb3.
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/types/blockchain.d.ts
Labels: publish

#2043 call UI fixed in terminal
  libs/remix-ui/terminal/src/lib/components/RenderCall.tsx
Labels: publish

#2046 Fix signature
  apps/remix-ide-e2e/src/tests/signingMessage.test.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
Labels: publish

#2059 fix user select
  libs/remix-ui/workspace/src/lib/css/file-explorer.css
Labels: publish

#2062 fix providing wrong evm version
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
Labels: publish

#2035 Newindexdb
  .circleci/config.yml
  apps/remix-ide-e2e/src/helpers/init.ts
  apps/remix-ide-e2e/src/tests/migrateFileSystem.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide-e2e/src/tests/recorder.test.ts
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/files/dgitProvider.js
  apps/remix-ide/src/app/files/fileManager.ts
  apps/remix-ide/src/app/files/fileProvider.js
  apps/remix-ide/src/app/panels/tab-proxy.js
  apps/remix-ide/src/app/plugins/storage.ts
  apps/remix-ide/src/assets/js/init.js
  apps/remix-ide/src/assets/js/lightning-fs.min.js
  apps/remix-ide/src/assets/js/migrate.js
  apps/remix-ide/src/index.html
  apps/remix-ide/src/lib/helper.js
  apps/remix-ide/src/production.index.html
  apps/remix-ide/src/remixAppManager.js
  libs/remix-core-plugin/src/lib/compiler-content-imports.ts
  libs/remix-debug/src/debugger/stepManager.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/solidity-unit-testing/src/lib/logic/testTabLogic.ts
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  package-lock.json
  package.json
  workspace.json
Labels: publish

#2072 Show error message when localstorage is full and restore default file content.
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/helper/src/lib/helper-components.tsx
Labels: bugfix

#2083 Fix retrieving events abi
  libs/remix-lib/src/execution/eventsDecoder.ts
Labels: publish

#2054 Import solidity standard json files via url param
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/types/index.ts
Labels: e2e-tests-needed, publish

#2106 Add e2e for json import via url parameter.
  apps/remix-ide-e2e/src/tests/url.spec.ts
Labels: browser-tests
