Repository remix-project-org/remix-project, pull requests merged in 2022-11, with the labels that each got.

#2984 Prevent proxy upgrade for invalid proxy address
  libs/remix-ui/run-tab/src/lib/actions/deploy.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
Labels: UX improvement

#3058 move language syntax highlighting for the Monaco Editor
  apps/remix-ide/src/app/editor/editor.js
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/editor/src/lib/syntaxes/move.ts
Labels: editor

#3066 Fix URL re-write
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix

#3070 matomo desktop
  apps/remix-ide/src/app.js
  apps/remix-ide/src/assets/js/loader.js
Labels: remix-desktop

#3131 Run and Deploy Spacing Fix
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: ready-for-review

#3148 Tooltip and Title Fix
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/deployInput.tsx
Labels: ready-for-review

#3130 Fix tooltip bug
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: ready-for-review

#3149 Fix Spacing in Solidity Compiler Button
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: ready-for-review

#3068 Improve gas in debugger
  apps/debugger/src/app/debugger-api.ts
  apps/remix-ide-e2e/src/commands/waitForElementContainsText.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  libs/remix-core-plugin/src/lib/offset-line-to-column-converter.ts
  libs/remix-debug/src/Ethdebugger.ts
  libs/remix-debug/src/debugger/debugger.ts
  libs/remix-debug/src/solidity-decoder/decodeInfo.ts
  libs/remix-debug/src/solidity-decoder/internalCallTree.ts
  libs/remix-debug/src/solidity-decoder/localDecoder.ts
  libs/remix-debug/src/solidity-decoder/solidityProxy.ts
  libs/remix-debug/src/solidity-decoder/types/StringType.ts
  libs/remix-debug/src/source/offsetToLineColumnConverter.ts
  libs/remix-debug/src/source/sourceLocationTracker.ts
  libs/remix-debug/test/decoder/localDecoder.ts
  libs/remix-debug/test/decoder/localsTests/int.ts
  libs/remix-ui/app/src/lib/remix-app/components/modals/matomo.tsx
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/idebugger-api.ts
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/assembly-items.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/vm-debugger-head.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/vm-debugger.tsx
  libs/remix-ui/debugger-ui/src/reducers/assembly-items.ts
Labels: ready-to-review

#3164 fix log to terminal
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: Solidity Unit Testing Plugin

#3168 fix debugging proxy contract
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-core-plugin/src/lib/compiler-artefacts.ts
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-core-plugin/src/lib/constants/uups.ts
  libs/remix-core-plugin/src/lib/openzeppelin-proxy.ts
  libs/remix-lib/src/util.ts
  libs/remix-lib/test/util.ts
Labels: ready-to-review

#3137 Tooltip Review Story Fixes
  apps/remix-ide-e2e/src/local-plugin/src/app/app.tsx
  apps/remix-ide-e2e/src/tests/libraryDeployment.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  libs/remix-ui/checkbox/src/lib/remix-ui-checkbox.tsx
  libs/remix-ui/helper/src/lib/components/custom-tooltip.tsx
  libs/remix-ui/helper/src/types/customtooltip.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/components/gasPrice.tsx
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/static-analyser/src/lib/Button/StaticAnalyserButton.tsx
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Home.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
  libs/remix-ui/workspace/src/lib/components/file-explorer-menu.tsx
Labels: ready-for-review
