Repository remix-project-org/remix-project, pull requests merged in 2022-09, with the labels that each got.

#2849 fix #2847
  apps/remix-ide/src/app/tabs/web3-provider.js
Labels: autorebase

#2850 fix definition provider
  libs/remix-ui/editor/src/lib/providers/definitionProvider.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: autorebase, bugfix

#2856 rm unused var
  libs/remix-ui/tree-view/src/types/index.ts
  libs/remix-ui/workspace/src/lib/components/file-render.tsx
Labels: autorebase

#2818 Maintain standard for root directory
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide/src/app/files/fileProvider.js
  apps/remix-ide/src/app/files/workspaceFileProvider.js
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/components/file-explorer.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/utils/constants.ts
Labels: fix, autorebase

#2851 fix feeding monaco with current file dependencies
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/editor/src/lib/web-types.ts
Labels: autorebase

#2858 fixing the selected color for autocomplete
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: autorebase

#2863 Fixdragdrop
  apps/remix-ide/src/app/files/fileManager.ts
Labels: autorebase

#2881 scroll bug fixing
  libs/remix-ui/app/src/lib/remix-app/style/remix-app.css
  libs/remix-ui/vertical-icons-panel/src/lib/components/IconList.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: autorebase

#2917 add imports to auto-complete
  apps/remix-ide-e2e/src/commands/addFile.ts
  apps/remix-ide/src/app/plugins/parser/code-parser.tsx
  apps/remix-ide/src/app/plugins/parser/services/code-parser-compiler.ts
  apps/remix-ide/src/app/plugins/parser/services/code-parser-imports.ts
  libs/remix-ui/editor/src/lib/providers/completion/completionGlobals.ts
  libs/remix-ui/editor/src/lib/providers/completion/contracts/contracts.txt
  libs/remix-ui/editor/src/lib/providers/completionProvider.ts
  libs/remix-ui/editor/src/lib/providers/definitionProvider.ts
  libs/remix-ui/search/src/index.ts
  package.json
  yarn.lock
Labels: autorebase

#2861 bug fixes
  apps/remix-ide-e2e/src/commands/addFile.ts
  apps/remix-ide-e2e/src/helpers/init.ts
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-flatly.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-spacelab.min.css
  apps/remix-ide/src/assets/css/themes/remix-dark_tvx1s2.css
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/panel/src/lib/plugins/remix-ui-panel.tsx
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
  libs/remix-ui/workspace/src/lib/css/remix-ui-workspace.css
Labels: autorebase

#2903 Add track workspace as new git repo
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: enhancement, UI

#2895 workspace template categories
  apps/remix-ide/webpack.config.js
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ws-templates/src/templates/ozerc20/index.ts
  libs/remix-ws-templates/src/templates/ozerc721/index.ts
  package.json
  yarn.lock
Labels: workspace templates, ready-to-review

#2926 fix compiler license loading
  libs/remix-solidity/src/compiler/compiler.ts
Labels: solidity compiler plugin

#2927 features for oz templates
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ws-templates/src/templates/ozerc1155/index.ts
  libs/remix-ws-templates/src/templates/ozerc20/index.ts
  libs/remix-ws-templates/src/templates/ozerc721/index.ts
Labels: workspace templates, ready-to-review

#2893 fix storageAt rpc call
  libs/remix-simulator/src/VmProxy.ts
  libs/remix-simulator/src/methods/blocks.ts
  libs/remix-simulator/test/blocks.ts
Labels: discussion

#2935 Script to generate a QA doc
  build-qa-doc.js
Labels: autorebase

#2943 fix path to create and open file from home tab
  apps/remix-ide-e2e/src/tests/homeTab.test.ts
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: WIP
