Repository remix-project-org/remix-project, pull requests merged in 2022-03, with the labels that each got.

#2113 Filesystem migration fallback
  apps/remix-ide-e2e/src/tests/migrateFileSystem.test.ts
  apps/remix-ide/src/app/components/preload.tsx
  apps/remix-ide/src/app/components/styles/preload.css
  apps/remix-ide/src/app/files/fileSystem.ts
  apps/remix-ide/src/app/files/filesystems/fileSystemUtility.ts
  apps/remix-ide/src/app/files/filesystems/indexedDB.ts
  apps/remix-ide/src/app/files/filesystems/localStorage.ts
  apps/remix-ide/src/app/plugins/storage.ts
  apps/remix-ide/src/app/tabs/theme-module.js
  apps/remix-ide/src/assets/js/init.js
  apps/remix-ide/src/assets/js/lightning-fs.min.js
  apps/remix-ide/src/assets/js/migrate.js
  apps/remix-ide/src/index.html
  apps/remix-ide/src/index.tsx
  apps/remix-ide/src/production.index.html
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
  libs/remix-ui/terminal/src/lib/terminalWelcome.tsx
  package.json
Labels: publish

#2129 typo
  apps/remix-ide/src/app/components/preload.tsx
  apps/remix-ide/src/app/files/filesystems/fileSystemUtility.ts
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: bug

#2092 Search
  apps/remix-ide-e2e/src/tests/search.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/components/vertical-icons.tsx
  apps/remix-ide/src/app/tabs/search.tsx
  apps/remix-ide/src/assets/img/Search_Icon.svg
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/app/src/index.ts
  libs/remix-ui/app/src/lib/remix-app/components/modals/modal-wrapper.tsx
  libs/remix-ui/app/src/lib/remix-app/context/provider.tsx
  libs/remix-ui/app/src/lib/remix-app/interface/index.ts
  libs/remix-ui/app/src/lib/remix-app/reducer/modals.ts
  libs/remix-ui/modal-dialog/src/lib/types/index.ts
  libs/remix-ui/search/.babelrc
  libs/remix-ui/search/.eslintrc.json
  libs/remix-ui/search/.prettierrc
  libs/remix-ui/search/src/index.ts
  libs/remix-ui/search/src/lib/components/Exclude.tsx
  libs/remix-ui/search/src/lib/components/Find.tsx
  libs/remix-ui/search/src/lib/components/Include.tsx
  libs/remix-ui/search/src/lib/components/OverWriteCheck.tsx
  libs/remix-ui/search/src/lib/components/Replace.tsx
  libs/remix-ui/search/src/lib/components/Search.tsx
  libs/remix-ui/search/src/lib/components/results/ResultFileName.tsx
  libs/remix-ui/search/src/lib/components/results/ResultItem.tsx
  libs/remix-ui/search/src/lib/components/results/ResultSummary.tsx
  libs/remix-ui/search/src/lib/components/results/Results.tsx
  libs/remix-ui/search/src/lib/components/results/SearchHelper.ts
  libs/remix-ui/search/src/lib/context/context.tsx
  libs/remix-ui/search/src/lib/reducers/Reducer.ts
  libs/remix-ui/search/src/lib/search.css
  libs/remix-ui/search/src/lib/types/index.ts
  libs/remix-ui/search/tsconfig.json
  libs/remix-ui/search/tsconfig.lib.json
  nx.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: autorebase, publish

#2122 fetch from etherscan while debugging
  apps/remix-ide-e2e/src/tests/editor.test.ts
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/plugins/config.ts
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-core-plugin/src/lib/helpers/fetch-etherscan.ts
  libs/remix-core-plugin/src/lib/helpers/fetch-sourcify.ts
  libs/remix-solidity/src/compiler/compiler-input.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/editor/src/lib/remix-ui-editor.css
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/settings/src/lib/constants.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
  libs/remix-ui/solidity-unit-testing/src/lib/css/style.css
Labels: autorebase, publish

#2138 update resolver
  apps/remix-ide-e2e/src/tests/importFromGithub.test.ts
  libs/remix-url-resolver/src/resolve.ts
  package.json
Labels: bug

#2149 caret for calls fixed
  libs/remix-ui/terminal/src/lib/components/RenderCall.tsx
Labels: bugfix, publish

#2160 Fix decoding events
  libs/remix-lib/src/execution/eventsDecoder.ts
Labels: publish

#2159 e2e for mocha testing added
  apps/remix-ide-e2e/src/tests/terminal.test.ts
Labels: browser-tests

#2143 readd gist prefix
  apps/remix-ide-e2e/src/tests/gist.test.ts
  apps/remix-ide/src/app/tabs/test-tab.js
  libs/remix-core-plugin/src/lib/gist-handler.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
Labels: publish

#2170 search fixes
  apps/remix-ide-e2e/src/tests/search.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/files/dgitProvider.js
  apps/remix-ide/src/app/tabs/search.tsx
  apps/remix-ide/src/assets/img/Search_Icon.svg
  apps/remix-ide/src/assets/img/search_icon.webp
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/editor/src/lib/actions/editor.ts
  libs/remix-ui/search/src/lib/components/Exclude.tsx
  libs/remix-ui/search/src/lib/components/Find.tsx
  libs/remix-ui/search/src/lib/components/FindContainer.tsx
  libs/remix-ui/search/src/lib/components/Include.tsx
  libs/remix-ui/search/src/lib/components/OverWriteCheck.tsx
  libs/remix-ui/search/src/lib/components/Replace.tsx
  libs/remix-ui/search/src/lib/components/Search.tsx
  libs/remix-ui/search/src/lib/components/Undo.tsx
  libs/remix-ui/search/src/lib/components/results/ResultItem.tsx
  libs/remix-ui/search/src/lib/components/results/ResultSummary.tsx
  libs/remix-ui/search/src/lib/components/results/Results.tsx
  libs/remix-ui/search/src/lib/components/results/SearchHelper.ts
  libs/remix-ui/search/src/lib/context/context.tsx
  libs/remix-ui/search/src/lib/reducers/Reducer.ts
  libs/remix-ui/search/src/lib/search.css
  libs/remix-ui/search/src/lib/types/index.ts
Labels: autorebase, publish

#2191 add clear local storage in settings
  apps/remix-ide-e2e/src/tests/generalSettings.test.ts
  apps/remix-ide/src/config.js
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
Labels: UI, publish

#2227 added storage layout in compilation details
  libs/remix-solidity/src/compiler/compiler-input.ts
  libs/remix-solidity/src/compiler/types.ts
  libs/remix-ui/solidity-compiler/src/lib/logic/contract-parser.ts
Labels: autorebase, publish

#2233 fix activation
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: autorebase

#2232 selected file UI fixed in Udapp
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
Labels: UDapp plugin

#2242 BETA: Disable auto-focus on compilation finished.
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
Labels: bugfix

#2241 Disable auto-focus on compilation finished.
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
Labels: bugfix

#2246 Update release-management.md
  release-management.md
Labels: effort: 1

#2240 do not show solidity
  apps/remix-ide/src/app.js
Labels: publish

#2208 Make sure we remove the current file from the previous session
  apps/remix-ide/src/app/files/fileManager.ts
Labels: autorebase, effort: 1
