Repository remix-project-org/remix-project, pull requests merged in 2022-10, with the labels that each got.

#2965 reset workspace options
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ws-templates/src/templates/ozerc1155/index.ts
  libs/remix-ws-templates/src/templates/ozerc20/index.ts
  libs/remix-ws-templates/src/templates/ozerc721/index.ts
Labels: ready-to-review

#2977 handle connections in plugins
  apps/remix-ide/src/app/files/foundry-handle.js
  apps/remix-ide/src/app/files/git-handle.js
  apps/remix-ide/src/app/files/hardhat-handle.js
  apps/remix-ide/src/app/files/slither-handle.js
  apps/remix-ide/src/app/files/truffle-handle.js
  apps/remix-ide/src/app/plugins/remixd-handle.tsx
Labels: bug

#2987 Dropdowncontracts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/payload.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/constants/index.ts
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  libs/remixd/src/services/hardhatClient.ts
Labels: bugfix

#2990 fix compilation result sync for truffle
  libs/remixd/src/services/truffleClient.ts
Labels: ready-to-review

#3032 fix link in debugger
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
Labels: ready-to-review

#2879 Switch and Checkout Branch
  apps/remix-ide/src/app/files/dgitProvider.js
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/helper/src/lib/remix-ui-helper.ts
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/actions/payload.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/css/remix-ui-workspace.css
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/utils/gitStatusFilter.ts
Labels: feature request

#2955 remove previous build file
  libs/remix-core-plugin/src/lib/compiler-metadata.ts
Labels: ready-to-review

#3026 fix issue 2980
  libs/remix-ui/panel/src/lib/plugins/panel.css
Labels: bugfix

#3007 update release-process
  release-process.md
Labels: ready-to-review
