Repository remix-project-org/remix-project, pull requests merged in 2022-04, with the labels that each got.

#2253 save slither report
  libs/remixd/src/services/slitherClient.ts
Labels: remixD

#2257 Fix Compile Button Text Overflow Issue
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: publish

#2270 create test libs on the fly
  apps/remix-ide/src/app/tabs/test-tab.js
  libs/remix-core-plugin/src/lib/compiler-content-imports.ts
Labels: Solidity Unit Testing Plugin, autorebase

#2262 UI for auto exec
  apps/remix-ide-e2e/src/tests/libraryDeployment.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/panels/layout.ts
  apps/remix-ide/src/app/tabs/compile-and-run.ts
  apps/remix-ide/src/app/tabs/intelligent-script-executor.ts
  apps/remix-ide/src/assets/css/themes/bootstrap-cerulean.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-flatly.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-spacelab.min.css
  apps/remix-ide/src/assets/css/themes/remix-black_undtds.css
  apps/remix-ide/src/assets/css/themes/remix-candy_ikhg4m.css
  apps/remix-ide/src/assets/css/themes/remix-dark_tvx1s2.css
  apps/remix-ide/src/assets/css/themes/remix-light_powaqg.css
  apps/remix-ide/src/assets/css/themes/remix-midcentury_hrzph3.css
  apps/remix-ide/src/remixAppManager.js
  apps/solidity-compiler/src/app/compiler-api.ts
  libs/remix-lib/src/types/ICompilerApi.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/css/style.css
  libs/remix-ui/workspace/src/lib/templates/examples.ts
Labels: UI, publish

#2271 add resources loaded by rawloader
  .circleci/config.yml
  apps/remix-ide/ci/deploy_from_travis_remix-alpha.sh
  apps/remix-ide/ci/deploy_from_travis_remix-beta.sh
  apps/remix-ide/ci/deploy_from_travis_remix-live.sh
Labels: publish

#2275 catch filepanel activation
  libs/remix-ui/search/src/lib/context/context.tsx
Labels: publish

#2292 Fix Metamask integration
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
Labels: publish

#2293 don't reset the connection if a call fails
  apps/remix-ide/src/app/tabs/abstract-provider.tsx
Labels: publish

#2297 added description to script templates
  apps/remix-ide-e2e/src/tests/search.test.ts
  libs/remix-ui/workspace/src/lib/templates/examples.ts
Labels: publish

#2314 fix eth_estimateGas
  libs/remix-simulator/src/methods/transactions.ts
Labels: publish

#2323 fix load with remix desktop
  apps/remix-ide/src/assets/js/loader.js
Labels: publish

#2324 wait to get tx receipt
  apps/remix-ide/src/app/tabs/web3-provider.js
Labels: publish
