Repository remix-project-org/remix-project, pull requests merged in 2022-01, with the labels that each got.

#1876 do not merge files for localhost workspace
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
Labels: remixD, publish

#1888 resolve remix-tests libs with Localhost workspace
  libs/remix-core-plugin/src/lib/compiler-content-imports.ts
Labels: remixD, Solidity Unit Testing Plugin

#1905 Remove focus for file closed in the editor
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/payload.ts
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
Labels: fix, publish

#1892 local compiler should be loaded without worker
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: WIP, on hold, publish

#1861 Fix vertical icons badge
  apps/remix-ide/src/app/components/vertical-icons.js
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/vertical-icons-panel/src/lib/components/Badge.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Debugger.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/OtherIcons.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/RequiredSection.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Settings.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Solidity.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/SolidityStaticAnalysis.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Udapp.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/reducers/iconBadgeReducer.ts
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.css
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.tsx
Labels: publish

#1914 update memory fetching flag
  libs/remix-debug/src/trace/traceManager.ts
Labels: remix-debug, publish

#1921 use onSelect from Tabs
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: publish

#1933 fix input encoding
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: UDapp plugin, publish

#1942 dragbar z-index fixed, removed Optimism, added Cairo
  apps/remix-ide/src/assets/img/cairoLogo.webp
  apps/remix-ide/src/remixAppManager.js
  libs/remix-core-plugin/src/lib/compiler-artefacts.ts
  libs/remix-ui/app/src/lib/remix-app/components/dragbar/dragbar.css
  libs/remix-ui/home-tab/src/lib/components/pluginButton.tsx
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.css
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  libs/remix-ui/panel/src/lib/dragbar/dragbar.css
  libs/remix-ui/run-tab/src/lib/actions/index.ts
Labels: publish

#1954 Home Tab: new file, open file fixed
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.css
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish

#1938 fix solidity warning in the editor
  libs/remix-ui/editor/src/lib/remix-ui-editor.css
Labels: publish

#1947 remember click
  libs/remix-ui/permission-handler/src/lib/permission-dialog.tsx
Labels: publish

#1952 SUT plugin fixes
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: publish

#1953 Fix recorder bugs
  apps/remix-ide/src/app/tabs/runTab/model/recorder.js
  libs/remix-ui/helper/src/lib/remix-ui-helper.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
Labels: fix, UDapp plugin, publish

#1908 Terminal fixes
  apps/remix-ide-e2e/src/tests/defaultLayout.test.ts
  apps/remix-ide/src/assets/css/themes/bootstrap-cerulean.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-flatly.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-spacelab.min.css
  apps/remix-ide/src/assets/css/themes/remix-black_undtds.css
  apps/remix-ide/src/assets/css/themes/remix-candy_ikhg4m.css
  apps/remix-ide/src/assets/css/themes/remix-dark_tvx1s2.css
  apps/remix-ide/src/assets/css/themes/remix-light_powaqg.css
  apps/remix-ide/src/assets/css/themes/remix-midcentury_hrzph3.css
  libs/remix-ui/terminal/src/lib/components/ChechTxStatus.tsx
  libs/remix-ui/terminal/src/lib/components/Context.tsx
  libs/remix-ui/terminal/src/lib/components/RenderCall.tsx
  libs/remix-ui/terminal/src/lib/components/RenderKnownTransactions.tsx
  libs/remix-ui/terminal/src/lib/components/RenderUnknownTransactions.tsx
  libs/remix-ui/terminal/src/lib/components/Table.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.css
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
  libs/remix-ui/terminal/src/lib/terminalWelcome.tsx
Labels: publish

#1958 Fix debugging live transactions
  apps/debugger/src/app/debugger-api.ts
  libs/remix-core-plugin/src/lib/compiler-content-imports.ts
Labels: bug, publish

#1959 hometab fixes
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.css
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish

#1976 fix css for tests
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: Solidity Unit Testing Plugin

#1965 terminal hide
  apps/remix-ide/src/app/panels/layout.ts
  libs/remix-ui/panel/src/lib/dragbar/dragbar.tsx
  libs/remix-ui/panel/src/lib/main/main-panel.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
Labels: publish

#1985 fixed icons paddings on verticalicons and PM selection from home
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Home.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.css
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.tsx
Labels: publish

#1995 add download backup in homepage
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish

#1996 Fix loop over references
  apps/remix-ide-e2e/src/commands/currentSelectedFileIs.ts
  apps/remix-ide-e2e/src/tests/editor.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app/editor/editor.js
  libs/remix-core-plugin/src/lib/editor-context-listener.ts
  libs/remix-ui/editor-context-view/src/lib/remix-ui-editor-context-view.tsx
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: publish

#1997 added Scam alert to home
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish

#1994 icons padding on verticals
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.css
Labels: publish

#2004 rename Cairo to StarkNet
  apps/remix-ide/src/assets/img/cairoLogo.webp
  apps/remix-ide/src/assets/img/starkNetLogo.webp
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish

#1989 loading performance improvement
  apps/remix-ide/src/app.js
  apps/remix-ide/src/index.tsx
  apps/remix-ide/tsconfig.json
Labels: WIP, publish

#2012 chunk loading fixed
  apps/remix-ide/src/app.js
  apps/remix-ide/webpack.config.js
Labels: publish

#2003 add restore backup
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: publish
