Repository remix-project-org/remix-project, pull requests merged in 2022-07, with the labels that each got.

#2530 fixing bug of saved path
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: publish

#2547 Add validationFn to the prompt modal to validate the input
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/providers.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/tabs/abstract-provider.tsx
  apps/remix-ide/src/app/tabs/external-http-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/app/src/lib/remix-app/components/modals/modal-wrapper.tsx
  libs/remix-ui/app/src/lib/remix-app/context/provider.tsx
  libs/remix-ui/app/src/lib/remix-app/interface/index.ts
  libs/remix-ui/app/src/lib/remix-app/reducer/modals.ts
  libs/remix-ui/app/src/lib/remix-app/state/modals.ts
  libs/remix-ui/helper/src/lib/helper-components.tsx
  libs/remix-ui/modal-dialog/src/lib/remix-ui-modal-dialog.tsx
  libs/remix-ui/modal-dialog/src/lib/types/index.ts
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
Labels: ready-to-review

#2590 fix contract dropdown in UDApp
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
Labels: UDapp plugin, ready-to-review

#2584 add L2 networks
  apps/remix-ide-e2e/src/commands/switchEnvironment.ts
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_11.test.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide-e2e/src/tests/providers.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/tabs/abstract-provider.tsx
  apps/remix-ide/src/app/tabs/injected-arbitrum-one-provider.tsx
  apps/remix-ide/src/app/tabs/injected-optimism-provider.tsx
  apps/remix-ide/src/app/tabs/injected-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/helper/src/index.ts
  libs/remix-ui/helper/src/lib/components/custom-dropdown.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/css/run-tab.css
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#2596 update project Readme Header
  README.md
Labels: ready-to-review

#2595 env name updated
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/src/app/tabs/external-http-provider.tsx
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
Labels: ready-to-review

#2598 Hide dgit icon if connected to localhost
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix, ready-to-review

#2613 bump remixd version
  libs/remixd/package.json
Labels: remixD, ready-to-review

#2619 Hide dropdown when interacting with file-explorer
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: fix, ready-for-review

#2615 update modals of proxy functionality
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-ui/helper/src/lib/helper-components.tsx
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: UI

#2626 Fix duplicate repository name and update clone error message
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: ready-for-review

#2631 Add e2e tests for clone repository feature.
  apps/remix-ide-e2e/src/tests/workspace.test.ts
Labels: browser-tests, ready-for-review

#2628 show toaster when compiler version is updated
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: ready-to-review

#2638 removed clone icon for localhost workspace
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#2634 Tooltip background fixed for light theme
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: ready-to-review

#2637 Catch uncaught transaction errors
  apps/remix-ide/src/blockchain/blockchain.js
Labels: fix, ready-for-review

#2642 create default workspace if no other workspace
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: ready-to-review

#2663 remove provider plugins from UI list
  apps/remix-ide/src/remixAppManager.js
Labels: ready-to-review

#2664 remixd readme updated
  libs/remixd/README.md
Labels: ready-to-review

#2702 fix console methods in terminal
  libs/remix-ui/terminal/src/lib/utils/wrapScript.ts
Labels: bugfix, ready-to-review
