Repository remix-project-org/remix-project, pull requests merged in 2023-07, with the labels that each got.

#3883 update doc link for etherscan plugin
  apps/etherscan/src/profile.json
Labels: ready-to-review, etherscan

#3891 Home Tab and SSA fixes
  apps/remix-ide/src/app/tabs/analysis-tab.js
  apps/remix-ide/src/app/tabs/locales/en/home.json
  libs/remix-ui/home-tab/src/lib/components/homeTabFeaturedPlugins.tsx
Labels: ready-to-review

#3892 SSA Improvements
  apps/remix-ide/src/app/tabs/analysis-tab.js
  libs/remix-ui/static-analyser/src/lib/ErrorRenderer.tsx
  libs/remix-ui/static-analyser/src/lib/actions/staticAnalysisActions.ts
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
  libs/remix-ui/static-analyser/src/staticanalyser.d.ts
Labels: ready-to-review

#3876 Static Analyzers Run Button Fix
  apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
  libs/remix-ui/static-analyser/src/lib/Button/StaticAnalyserButton.tsx
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: ready-to-review

#3918 fix expanded method call
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: UDapp plugin, ready-to-review

#3919 fix class for tx details 'from'
  libs/remix-ui/terminal/src/lib/components/Table.tsx
Labels: UI, ready-to-review

#3920 update message to make GUID more clear
  apps/etherscan/src/app/utils/verify.ts
Labels: ready-to-review, etherscan

#3921 SSA-QA-Patch
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
Labels: ready-to-review

#3926 fix tooltip for disabled method call buttons
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: UDapp plugin
