Repository remix-project-org/remix-project, pull requests merged in 2023-01, with the labels that each got.

#3262 Fix resolver
  libs/remix-url-resolver/package.json
Labels: fix

#3266 Return empty array for undefined nextIndexes
  libs/remix-ui/debugger-ui/src/reducers/assembly-items.ts
Labels: fix

#3282 fix circle checkout
  .circleci/config.yml
Labels: bug

#3281 fix hide warnings
  apps/solidity-compiler/src/app/compiler-api.ts
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
Labels: solidity compiler plugin, ready-to-review

#3290 send matomo data to secondary server
  apps/remix-ide/src/assets/js/loader.js
Labels: ready-to-review

#3296 remove git from plugin list
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/plugins/remixd-handle.tsx
  apps/remix-ide/src/remixAppManager.js
Labels: plugins, ready-to-review

#3295 do not throw if ast not present
  libs/remix-debug/src/solidity-decoder/internalCallTree.ts
  libs/remix-debug/src/solidity-decoder/solidityProxy.ts
Labels: ready-to-review

#3255 Quick Updates to HomeTab
  apps/remix-ide/src/app/tabs/locales/en/home.json
  apps/remix-ide/src/app/tabs/locales/zh/home.json
  apps/remix-ide/src/assets/img/dgit.webp
  apps/remix-ide/src/assets/img/oneclickdapp.webp
  libs/remix-ui/home-tab/src/lib/components/homeTabFeaturedPlugins.tsx
  libs/remix-ui/home-tab/src/lib/components/homeTabGetStarted.tsx
  libs/remix-ui/home-tab/src/lib/components/homeTabLearn.tsx
Labels: WIP

#3299 re-add assets for remix libs
  libs/remix-analyzer/project.json
  libs/remix-astwalker/project.json
  libs/remix-debug/project.json
  libs/remix-lib/project.json
  libs/remix-simulator/project.json
  libs/remix-solidity/project.json
  libs/remix-url-resolver/project.json
  libs/remix-ws-templates/project.json
Labels: bugfix

#3285 fix remixd
  .circleci/config.yml
  libs/remixd/src/services/foundryClient.ts
  libs/remixd/src/services/hardhatClient.ts
  libs/remixd/src/services/truffleClient.ts
Labels: bug

#3301 bump remixd to 0.6.11
  libs/remixd/package.json
Labels: remixD

#3305 Fixed url overwrite
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
Labels: fix

#3306 Home Tab Quick Updates Fix
  libs/remix-ui/home-tab/src/lib/components/homeTabLearn.tsx
Labels: ready-for-review
