Repository remix-project-org/remix-project, pull requests merged in 2023-03, with the labels that each got.

#3478 Fix providers
  apps/remix-ide/src/app/providers/abstract-provider.tsx
  apps/remix-ide/src/app/providers/injected-provider.tsx
  apps/remix-ide/src/app/providers/mainnet-vm-fork-provider.tsx
Labels: remix-beta

#3480 bump 0.31.1
  package.json
Labels: remix-beta

#3479 mefdia icons alignement
  libs/remix-ui/home-tab/src/lib/components/homeTabTitle.tsx
Labels: ready-to-review

#3432 Line distance decreased for compilation details
  libs/remix-ui/solidity-compiler/src/lib/css/style.css
Labels: ready-to-review

#3458 Updated logo for browser tab title to colored one
  apps/remix-ide/src/assets/img/remix-logo-blue.png
  apps/remix-ide/src/index.html
  apps/remix-ide/src/webpack.index.html
Labels: ready-to-review

#3468 Focus on Home after refresh
  apps/remix-ide/src/app.js
Labels: autorebase, ready-to-review

#3453 fixed bg for sign msg modal
  libs/remix-ui/run-tab/src/lib/components/account.tsx
Labels: autorebase, ready-to-review

#3485 Move monaco out of bundle
  apps/remix-ide/src/app/plugins/parser/services/code-parser-compiler.ts
  apps/remix-ide/webpack.config.js
  libs/remix-ui/editor/src/index.ts
  libs/remix-ui/editor/src/lib/actions/editor.ts
  libs/remix-ui/editor/src/lib/providers/completion/completionGlobals.ts
  libs/remix-ui/editor/src/lib/providers/completionProvider.ts
  libs/remix-ui/editor/src/lib/providers/hoverProvider.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  package.json
  yarn.lock
Labels: ready-to-review

#3496 replace function
  apps/remix-ide-e2e/src/commands/journalLastChildIncludes.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide-e2e/src/tests/specialFunctions.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
Labels: autorebase, ready-to-review

#3498 use yarn cache for deploy
  .circleci/config.yml
Labels: autorebase, ready-to-review

#3488 remove jest
  apps/debugger/tsconfig.app.json
  apps/etherscan/tsconfig.app.json
  apps/remix-ide-e2e/src/local-plugin/.eslintrc
  apps/remix-ide/tsconfig.json
  apps/remix-ide/tsconfig.spec.json
  apps/solidity-compiler/tsconfig.app.json
  jest.preset.js
  libs/ghaction-helper/tsconfig.json
  libs/remix-solidity/jest.config.js
  libs/remix-solidity/tsconfig.json
  libs/remix-tests/tsconfig.spec.json
  libs/remixd/tsconfig.spec.json
  package.json
  yarn.lock
Labels: autorebase, ready-to-review

#3494 group test
  apps/remix-ide-e2e/src/tests/recorder.test.ts
Labels: ready-to-review

#3495 Misc fixes
  apps/remix-ide/src/app/tabs/compile-and-run.ts
  libs/remix-ui/settings/src/lib/github-settings.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: fix

#3502 restored Download in right click menu
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  apps/remix-ide/src/app/tabs/locales/zh/filePanel.json
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
Labels: remix-beta

#3500 No need to request access in async
  apps/remix-ide/src/app/providers/injected-provider.tsx
Labels: remix-beta

#3483 Sol2UML Default Message Patch
  libs/remix-ui/solidity-uml-gen/src/lib/solidity-uml-gen.tsx
Labels: ready-to-review

#3395 Add download Button and Matomo Integration to Sol2Uml plugin
  apps/remix-ide/src/app/plugins/contractFlattener.tsx
  apps/remix-ide/src/app/plugins/solidity-umlgen.tsx
  apps/remix-ide/src/app/tabs/locales/en/solUmlgen.json
  apps/remix-ide/src/app/tabs/locales/zh/solUmlgen.json
  libs/remix-ui/solidity-uml-gen/src/lib/components/UmlDownload.tsx
  libs/remix-ui/solidity-uml-gen/src/lib/css/solidity-uml-gen.css
  libs/remix-ui/solidity-uml-gen/src/lib/solidity-uml-gen.tsx
  libs/remix-ui/solidity-uml-gen/src/lib/utilities/UmlDownloadStrategy.ts
  package.json
  yarn.lock
Labels: ready-to-review

#3493 fix addfile & remixd
  apps/remix-ide-e2e/src/commands/addFile.ts
  apps/remix-ide-e2e/src/tests/remixd.test.ts
Labels: autorebase, ready-to-review

#3505 predeploy
  .circleci/config.yml
Labels: autorebase, ready-to-review

#3503 Pass custom provider options and publish dev libs
  libs/ghaction-helper/package.json
  libs/ghaction-helper/src/methods.ts
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-lib/package.json
  libs/remix-simulator/package.json
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-tests/src/run.ts
  libs/remix-tests/tests/testRunner.cli.spec.ts
  libs/remix-url-resolver/package.json
  libs/remix-ws-templates/package.json
Labels: gh-action

#3509 fix deploys
  .circleci/config.yml
  apps/remix-ide/ci/deploy_from_travis_remix-alpha.sh
  apps/remix-ide/ci/deploy_from_travis_remix-beta.sh
  apps/remix-ide/ci/deploy_from_travis_remix-live.sh
Labels: autorebase, ready-to-review

#3508 Update default project name
  apps/remix-ide/src/app/panels/file-panel.js
  libs/remix-ui/home-tab/src/lib/components/homeTabGetStarted.tsx
  libs/remix-ui/workspace/src/index.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/utils/constants.ts
Labels: ready-to-review

#3517 Fix generating unit-tests accounts lib
  apps/remix-ide/src/app/tabs/test-tab.js
  libs/remix-tests/sol/tests_accounts.sol.ts
  libs/remix-tests/src/compiler.ts
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: ready-to-review

#3519 UI fixes in UDAPP
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/css/run-tab.css
Labels: ready-to-review

#3510 Resolve pending requests to remix-simulator after initialization is completed
  libs/ghaction-helper/package.json
  libs/ghaction-helper/src/methods.ts
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-lib/package.json
  libs/remix-simulator/package.json
  libs/remix-simulator/src/provider.ts
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-tests/src/run.ts
  libs/remix-tests/src/runTestFiles.ts
  libs/remix-tests/tests/testRunner.cli.spec.ts
  libs/remix-url-resolver/package.json
  libs/remix-ws-templates/package.json
Labels: gh-action

#3481 Decrease the setInterval timeout and use injected api to update accounts list and chain context
  apps/debugger/webpack.config.js
  apps/etherscan/webpack.config.js
  apps/remix-ide-e2e/src/local-plugin/webpack.config.js
  apps/remix-ide/src/app/providers/injected-provider.tsx
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/blockchain/providers/injected.js
  apps/remix-ide/src/blockchain/providers/node.js
  apps/remix-ide/src/blockchain/providers/vm.js
  apps/remix-ide/webpack.config.js
  apps/solidity-compiler/webpack.config.js
  apps/vyper/webpack.config.js
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/deploy.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/actions/payload.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/constants/index.ts
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/types/blockchain.d.ts
  libs/remix-ui/run-tab/src/lib/types/injected.d.ts
  libs/remix-ui/run-tab/src/lib/types/node.d.ts
  libs/remix-ui/run-tab/src/lib/types/vm.d.ts
Labels: ready-to-review

#3531 Update settings
  apps/remix-ide-e2e/src/tests/editorHoverContext.test.ts
  apps/remix-ide-e2e/src/tests/editorReferences.test.ts
  apps/remix-ide-e2e/src/tests/editor_error_marker.test.ts
  apps/remix-ide-e2e/src/tests/editor_line_text.test.ts
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/editor/src/lib/providers/completionProvider.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
Labels: ready-to-review

#3504 Download Workspace
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/helper/src/lib/components/custom-dropdown.tsx
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: file-explorer, ready-to-review

#3454 add trustwallet provider
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/providers/basic-injected-provider.tsx
  apps/remix-ide/src/app/providers/injected-L2-provider.tsx
  apps/remix-ide/src/app/providers/injected-provider-default.tsx
  apps/remix-ide/src/app/providers/injected-provider-trustwallet.tsx
  apps/remix-ide/src/app/providers/injected-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/run-tab/src/lib/actions/events.ts
Labels: ready-to-review

#3533 Add copy to clipboard to warning message
  libs/remix-ui/renderer/src/lib/renderer.css
  libs/remix-ui/renderer/src/lib/renderer.tsx
Labels: WIP, fix

#3543 Matomo bug fix: remove curley brace
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger-item.tsx
Labels: bug

#3530 fix creating vm acount
  apps/remix-ide/src/blockchain/providers/vm.js
  apps/remix-ide/src/blockchain/providers/worker-vm.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
Labels: bugfix, ready-to-review

#3552 show relevant error message
  apps/remix-ide/src/app/providers/injected-provider.tsx
Labels: providers

#3554 fix compilation warnings from script.sol while running free function
  apps/remix-ide/src/app/plugins/solidity-script.tsx
Labels: ready-to-review

#3573 Flakyballot fix
  apps/remix-ide-e2e/src/tests/ballot_0_4_14.test.ts
Labels: autorebase

#3575 Fix creating open zeppelin erc20 from home page
  libs/remix-ws-templates/src/templates/ozerc20/index.ts
Labels: fix, ready-to-review

#3578 Add "injected" even if no provider
  apps/remix-ide/src/app/udapp/run-tab.js
Labels: ready-to-review
