Repository remix-project-org/remix-project, pull requests merged in 2023-10, with the labels that each got.

#4107 show erc list in editor
  libs/remix-ui/editor/src/lib/providers/completion/completionGlobals.ts
Labels: editor, ready-to-review

#4138 adding missing colors to card-titles
  apps/remix-ide/src/assets/css/themes/bootstrap-cerulean.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-flatly.min.css
  apps/remix-ide/src/assets/css/themes/bootstrap-spacelab.min.css
  apps/remix-ide/src/assets/css/themes/remix-candy_ikhg4m.css
  apps/remix-ide/src/assets/css/themes/remix-light_powaqg.css
  apps/remix-ide/src/assets/css/themes/remix-midcentury_hrzph3.css
  apps/remix-ide/src/assets/css/themes/remix-unicorn.css
  apps/remix-ide/src/assets/css/themes/remix-violet.css
Labels: remix-beta

#4139 bump beta version to 0.36.3
  package.json
Labels: remix-beta

#4143 Oz proxy backwards compatible
  apps/remix-ide-e2e/src/tests/proxy_oz_v4.test.ts
  apps/remix-ide-e2e/src/tests/proxy_oz_v5.test.ts
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-core-plugin/src/lib/constants/uups.ts
  libs/remix-core-plugin/src/lib/openzeppelin-proxy.ts
Labels: bug

#4072 make function stack clickable
  libs/remix-debug/src/solidity-decoder/internalCallTree.ts
  libs/remix-debug/test/decoder/localsTests/int.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.css
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/dropdown-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/function-panel.tsx
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/vm-debugger-head.tsx
  libs/remix-ui/debugger-ui/src/types/index.ts
Labels: ready-to-review

#4106 add missing api to the filemanager
  apps/remix-ide/src/app/files/fileManager.ts
Labels: ready-to-review

#4153 Move compilation details to Main panel plugin
  .prettierrc.json
  apps/compile-details/project.json
  apps/compile-details/src/index.html
  apps/compile-details/tsconfig.app.json
  apps/compile-details/tsconfig.json
  apps/compile-details/webpack.config.js
  apps/remix-ide-e2e/src/commands/verifyContracts.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/plugins/compile-details.tsx
  apps/remix-ide/src/app/tabs/locales/en/solidity.json
  apps/remix-ide/src/app/tabs/locales/es/solidity.json
  apps/remix-ide/src/app/tabs/locales/fr/solidity.json
  apps/remix-ide/src/app/tabs/locales/zh/solidity.json
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/solidity-compile-details/src/index.ts
  libs/remix-ui/solidity-compile-details/src/lib/solidity-compile-details.tsx
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
  libs/remix-ui/solidity-compiler/src/lib/css/style.css
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
  libs/remix-ui/solidity-compiler/src/lib/types/index.ts
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
  tsconfig.paths.json
Labels: ready-to-review

#4172 bump beta version to 0.38.4
  package.json
Labels: remix-beta

#4144 Circuit compiler UI
  apps/circuit-compiler/project.json
  apps/circuit-compiler/src/app/actions/index.ts
  apps/circuit-compiler/src/app/app.tsx
  apps/circuit-compiler/src/app/components/actions.tsx
  apps/circuit-compiler/src/app/components/compileBtn.tsx
  apps/circuit-compiler/src/app/components/configToggler.tsx
  apps/circuit-compiler/src/app/components/configurations.tsx
  apps/circuit-compiler/src/app/components/container.tsx
  apps/circuit-compiler/src/app/components/feedback.tsx
  apps/circuit-compiler/src/app/components/feedbackAlert.tsx
  apps/circuit-compiler/src/app/components/options.tsx
  apps/circuit-compiler/src/app/components/r1csBtn.tsx
  apps/circuit-compiler/src/app/components/versions.tsx
  apps/circuit-compiler/src/app/components/witness.tsx
  apps/circuit-compiler/src/app/components/witnessToggler.tsx
  apps/circuit-compiler/src/app/contexts/index.ts
  apps/circuit-compiler/src/app/reducers/state.ts
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/circuit-compiler/src/app/types/index.ts
  apps/circuit-compiler/src/css/app.css
  apps/circuit-compiler/src/example/hash.circom
  apps/circuit-compiler/src/example/simple.circom
  apps/circuit-compiler/src/index.html
  apps/circuit-compiler/src/profile.json
  apps/circuit-compiler/src/snarkjs.min.js
  apps/remix-ide/src/app/files/fileManager.ts
  apps/remix-ide/src/app/files/fileProvider.js
  apps/remix-ide/src/app/tabs/locales/en/circuit.json
  apps/remix-ide/src/app/tabs/locales/en/index.js
  apps/remix-ide/src/app/tabs/locales/es/circuit.json
  apps/remix-ide/src/app/tabs/locales/fr/circuit.json
  apps/remix-ide/src/app/tabs/locales/zh/circuit.json
  apps/remix-ide/src/app/tabs/locales/zh/index.js
  apps/remix-ide/src/assets/img/circom-icon-bw-800b.webp
  apps/remix-ide/src/assets/img/circom.webp
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/helper/src/lib/remix-ui-helper.ts
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
  package.json
  pkg/index.js
  yarn.lock
Labels: ready-to-review, documentation-needed

#4164 Semaphore template
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/actions/payload.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/components/file-explorer.tsx
  libs/remix-ui/workspace/src/lib/components/file-render.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/constants.ts
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/templates/semaphore/README.txt
  libs/remix-ws-templates/src/templates/semaphore/circuits/semaphore.circom
  libs/remix-ws-templates/src/templates/semaphore/circuits/simple.circom
  libs/remix-ws-templates/src/templates/semaphore/circuits/tree.circom
  libs/remix-ws-templates/src/templates/semaphore/index.ts
  libs/remix-ws-templates/src/templates/semaphore/scripts/run_setup.ts
  libs/remix-ws-templates/src/templates/semaphore/scripts/run_verification.ts
  libs/remix-ws-templates/src/templates/semaphore/templates/groth16_verifier.sol.ejs
Labels: ready-to-review

#4129 update parser
  apps/remix-ide/src/assets/js/parser/antlr.js
Labels: bug, ready-to-review

#3654 recent workspaces & Start Coding
  apps/remix-ide-e2e/src/tests/homeTab.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide/src/app/files/fileManager.ts
  apps/remix-ide/src/app/panels/file-panel.js
  apps/remix-ide/src/app/tabs/locales/en/home.json
  apps/remix-ide/src/app/tabs/locales/fr/home.json
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/home-tab/src/lib/components/homeTabFile.tsx
  libs/remix-ui/home-tab/src/lib/components/homeTabGetStarted.tsx
  libs/remix-ui/plugin-manager/src/lib/components/LocalPluginForm.tsx
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/constants.ts
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/templates/playground/.prettierrc
  libs/remix-ws-templates/src/templates/playground/README.txt
  libs/remix-ws-templates/src/templates/playground/contracts/helloWorld.sol
  libs/remix-ws-templates/src/templates/playground/index.ts
  libs/remix-ws-templates/src/templates/playground/scripts/deploy_with_ethers.ts
  libs/remix-ws-templates/src/templates/playground/scripts/deploy_with_web3.ts
  libs/remix-ws-templates/src/templates/playground/scripts/ethers-lib.ts
  libs/remix-ws-templates/src/templates/playground/scripts/web3-lib.ts
Labels: ready-to-review
