Repository remix-project-org/remix-project, pull requests merged in 2023-12, with the labels that each got.

#4273 Added Enter Dialog.
  apps/remix-ide-e2e/src/helpers/init.ts
  apps/remix-ide-e2e/src/tests/migrateFileSystem.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/assets/css/themes/remix-light_powaqg.css
  apps/remix-ide/src/walkthroughService.js
  libs/remix-ui/app/src/lib/remix-app/components/modals/enter.tsx
  libs/remix-ui/app/src/lib/remix-app/components/modals/matomo.tsx
  libs/remix-ui/app/src/lib/remix-app/interface/index.ts
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/app/src/lib/remix-app/types/index.ts
  libs/remix-ui/home-tab/src/lib/components/workspaceTemplate.tsx
Labels: UI, ready-to-review

#4243 Add uniswap template
  apps/remix-ide-e2e/src/tests/workspace_git.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/home-tab/src/lib/components/homeTabGetStarted.tsx
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/constants.ts
Labels: autorebase

#4302 walkthrough for recorder
  apps/remix-ide-e2e/src/tests/walkthrough.test.ts
  apps/remix-ide/src/app/tabs/locales/en/udapp.json
  apps/remix-ide/src/app/tabs/locales/fr/home.json
  apps/remix-ide/src/index.css
  apps/remix-ide/src/walkthroughService.js
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
  package.json
Labels: autorebase, ready-to-review

#4292 left highlight for active plugin icon
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/remix-ui-vertical-icons-panel.css
Labels: UI

#4303 style fixes on enter dialog
  libs/remix-ui/app/src/lib/remix-app/components/modals/enter.tsx
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
Labels: ready-to-review

#4312 typos and black theme bg color fix
  apps/remix-ide/src/assets/css/themes/remix-black_undtds.css
  apps/remix-ide/src/walkthroughService.js
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
Labels: autorebase

#4320 fix recorder walkthrough text
  apps/remix-ide/src/walkthroughService.js
Labels: ready-to-review
