Repository remix-project-org/remix-project, pull requests merged in 2023-04, with the labels that each got.

#3602 Sol2UML Portait Pdf Download Fix
  apps/remix-ide/src/app/plugins/contractFlattener.tsx
  apps/remix-ide/src/app/plugins/solidity-umlgen.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/flattenerUtilities.ts
  libs/remix-ui/solidity-uml-gen/src/lib/utilities/UmlDownloadStrategy.ts
Labels: ready-to-review

#3601 Unwanted Event Listener removal for Docgen
  apps/doc-gen/src/app/App.tsx
  apps/doc-gen/src/app/docgen-client.ts
Labels: ready-to-review

#3609 Style Generated UML in Sol2Uml Plugin
  apps/remix-ide/src/app/plugins/solidity-umlgen.tsx
  libs/remix-ui/solidity-uml-gen/src/types/index.ts
Labels: ready-to-review

#3606 Etherscan plugin improvements
  apps/etherscan/src/app/views/CaptureKeyView.tsx
  apps/etherscan/src/app/views/HomeView.tsx
  apps/etherscan/src/app/views/ReceiptsView.tsx
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan

#3613 allow scientific notation
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  libs/remix-lib/src/execution/txHelper.ts
  package.json
  yarn.lock
Labels: ready-to-review

#3622 Fix version import
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
  libs/remix-url-resolver/src/resolve.ts
  package.json
  yarn.lock
Labels: fix, ready-to-review

#3598 Fix save blocks ref
  apps/remix-ide-e2e/src/commands/verifyCallReturnValue.ts
  apps/remix-ide-e2e/src/tests/blockchain.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app/providers/mainnet-vm-fork-provider.tsx
  apps/remix-ide/src/blockchain/blockchain.tsx
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-debug/src/code/codeUtils.ts
  libs/remix-debug/src/trace/traceManager.ts
  libs/remix-lib/src/execution/forkAt.ts
  libs/remix-lib/src/execution/txRunner.ts
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-simulator/src/genesis.ts
  libs/remix-simulator/src/methods/transactions.ts
  libs/remix-simulator/src/provider.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-simulator/test/blocks.ts
Labels: fix, ready-to-review

#3632 Show textbox for constructor arguments conditionally
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan

#3659 Fix tooltip in SUT plugin
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: Solidity Unit Testing Plugin

#3657 updated github settings title and inf`
  apps/remix-ide/src/app/tabs/locales/en/settings.json
Labels: autorebase

#3563 updated warning for github settings
  apps/remix-ide-e2e/src/tests/workspace_git.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: autorebase
