Repository remix-project-org/remix-project, pull requests merged in 2023-05, with the labels that each got.

#3667 Fixsolc
  .circleci/config.yml
  apps/remix-ide/.gitignore
  apps/remix-ide/ci/download_e2e_assets.js
  apps/remix-ide/ci/downloadsoljson.sh
  apps/remix-ide/project.json
  apps/remix-ide/webpack.config.js
Labels: autosquash

#3674 fix compile and run
  apps/remix-ide/src/app/tabs/compile-and-run.ts
Labels: bugfix

#3678 Fix estimateGas when maxFee is fluctuating
  libs/remix-lib/src/execution/txRunnerWeb3.ts
Labels: bugfix

#3679 Fix estimateGas when maxFee is fluctuating
  libs/remix-lib/src/execution/txRunnerWeb3.ts
Labels: remix-beta

#3675 fix adding breakpoint
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: bugfix

#3699 Fix from exponential and Bump Libs
  libs/ghaction-helper/package.json
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-lib/package.json
  libs/remix-simulator/package.json
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-url-resolver/package.json
  libs/remix-ws-templates/package.json
Labels: fix

#3716 Fix wallet connect
  apps/walletconnect/src/app/app.tsx
  apps/walletconnect/src/app/walletConnectUI.tsx
  apps/walletconnect/src/services/RemixClient.ts
Labels: fix, ready-to-review

#3676 Contract flattener tests
  apps/remix-ide-e2e/src/tests/contract_flattener.test.ts
Labels: ready-to-review

#3726 Sol2uml e2e Tests
  apps/remix-ide-e2e/src/tests/sol2uml.test.ts
  libs/remix-ui/solidity-uml-gen/src/lib/components/UmlDownload.tsx
  libs/remix-ui/solidity-uml-gen/src/lib/solidity-uml-gen.tsx
Labels: WIP

#3707 Add 'web3 scripts' (to FE context menu)
  apps/remix-ide-e2e/src/tests/erc721.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide-e2e/src/tests/workspace_git.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger-item.tsx
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/scripts/contract-deployer/basic-contract-deploy.ts
  libs/remix-ui/workspace/src/lib/scripts/contract-deployer/create2-factory-deploy.ts
  libs/remix-ui/workspace/src/lib/scripts/contract-deployer/index.ts
  libs/remix-ui/workspace/src/lib/scripts/etherscan/index.ts
  libs/remix-ui/workspace/src/lib/scripts/etherscan/receiptGuidScript.ts
  libs/remix-ui/workspace/src/lib/scripts/etherscan/verifyScript.ts
  libs/remix-ui/workspace/src/lib/scripts/index.ts
Labels: translation, documentation-needed

#3744 show text field to enter values for constructor args
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan
