Repository remix-project-org/remix-project, pull requests merged in 2023-11, with the labels that each got.

#4178 Compilation details cleanup
  apps/compile-details/project.json
  apps/compile-details/src/index.html
  apps/compile-details/tsconfig.app.json
  apps/compile-details/tsconfig.json
  apps/compile-details/webpack.config.js
  apps/remix-ide/src/remixAppManager.js
Labels: ready-to-review

#4177 added basescan mainnet support
  apps/etherscan/src/app/utils/networks.ts
Labels: etherscan

#4179 create lang selector component
  libs/remix-ui/home-tab/src/lib/components/homeTablangOptions.tsx
  libs/remix-ui/home-tab/src/lib/components/types/carouselTypes.ts
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.tsx
Labels: ready-to-review

#4188 updated contribution and best practices files
  CONTRIBUTING.md
  team-best-practices.md
Labels: documentation

#4200 fix encoding boolean
  libs/remix-lib/src/execution/txHelper.ts
Labels: bugfix

#4199 language btn style changes
  libs/remix-ui/home-tab/src/lib/components/homeTablangOptions.tsx
Labels: ready-to-review

#4204 Fix using toBN
  libs/remix-ui/run-tab/src/lib/components/mainnet.tsx
Labels: bugfix

#4210 bump version to 0.37.1
  package.json
Labels: remix-beta

#4216 Remix beta: fix bsc
  apps/remix-ide/src/blockchain/execution-context.js
  libs/ghaction-helper/src/methods.ts
  libs/remix-lib/src/execution/txRunnerWeb3.ts
  libs/remix-ui/terminal/src/lib/components/Table.tsx
Labels: remix-beta

#4184 E2E: Circom Plugin
  apps/circuit-compiler/src/app/components/compileBtn.tsx
  apps/circuit-compiler/src/app/components/container.tsx
  apps/circuit-compiler/src/app/components/feedback.tsx
  apps/circuit-compiler/src/app/components/options.tsx
  apps/circuit-compiler/src/app/components/r1csBtn.tsx
  apps/circuit-compiler/src/app/components/witness.tsx
  apps/circuit-compiler/src/app/components/witnessToggler.tsx
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/remix-ide-e2e/src/tests/circom.test.ts
  libs/remix-ui/solidity-compiler/src/lib/api/compiler-api.ts
Labels: browser-tests

#4223 remix-beta: Fix logging calls
  libs/remix-ui/terminal/src/lib/components/Context.tsx
Labels: remix-beta

#4226 Hash checker circom workspace template
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/constants.ts
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/templates/hashchecker/README.txt
  libs/remix-ws-templates/src/templates/hashchecker/circuits/calculate_hash.circom
  libs/remix-ws-templates/src/templates/hashchecker/index.ts
  libs/remix-ws-templates/src/templates/hashchecker/scripts/run_setup.ts
  libs/remix-ws-templates/src/templates/hashchecker/scripts/run_verification.ts
  libs/remix-ws-templates/src/templates/hashchecker/templates/groth16_verifier.sol.ejs
Labels: ready-to-review

#4228 support submodules
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide/src/app/files/dgitProvider.js
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/workspace/src/lib/actions/payload.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/reducers/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  package.json
  yarn.lock
Labels: autorebase

#4229 consider remappings while compilation
  libs/remix-solidity/src/compiler/compiler-input.ts
  libs/remix-solidity/src/compiler/compiler.ts
  libs/remix-solidity/src/compiler/types.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
Labels: WIP

#4242 Rln template
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/circuit-compiler/src/app/types/index.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/constants.ts
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/templates/rln/LICENSE-APACHE
  libs/remix-ws-templates/src/templates/rln/LICENSE-MIT
  libs/remix-ws-templates/src/templates/rln/README.md
  libs/remix-ws-templates/src/templates/rln/circuits/rln.circom
  libs/remix-ws-templates/src/templates/rln/circuits/utils.circom
  libs/remix-ws-templates/src/templates/rln/circuits/withdraw.circom
  libs/remix-ws-templates/src/templates/rln/index.ts
  libs/remix-ws-templates/src/templates/rln/scripts/run_setup.ts
  libs/remix-ws-templates/src/templates/rln/templates/groth16_verifier.sol.ejs
Labels: ready-to-review

#4248 refactored UI of templates on hometab
  apps/remix-ide/src/assets/css/themes/bootstrap-cyborg.min.css
  apps/remix-ide/src/assets/img/gnosissafeLogo.png
  apps/remix-ide/src/assets/img/openzeppelinLogo.png
  apps/remix-ide/src/assets/img/oxprojectLogo.png
  apps/remix-ide/src/assets/img/remixverticaltextLogo.png
  apps/remix-ide/src/blockchain/execution-context.js
  libs/ghaction-helper/src/methods.ts
  libs/remix-ui/home-tab/src/lib/components/homeTabFeaturedPlugins.tsx
  libs/remix-ui/home-tab/src/lib/components/homeTabGetStarted.tsx
  libs/remix-ui/home-tab/src/lib/components/workspaceTemplate.tsx
  libs/remix-ui/home-tab/src/lib/remix-ui-home-tab.css
Labels: UI, UX Meeting

#4247 Update homeTablangOptions.tsx for light theme
  libs/remix-ui/home-tab/src/lib/components/homeTablangOptions.tsx
Labels: ready-to-review

#4267 added e2e to verify remappings
  apps/remix-ide-e2e/src/tests/ballot.test.ts
Labels: ready-to-review

#4253 Improve model
  apps/remix-ide/src/app/plugins/copilot/suggestion-service/copilot-suggestion.ts
  libs/remix-ui/editor/src/lib/providers/inlineCompletionProvider.ts
Labels: autorebase

#4269 Add slide in Featured section to show latest release highlights
  apps/remix-ide/src/app/tabs/locales/en/homeReleaseDetails.json
  apps/remix-ide/src/app/tabs/locales/en/index.js
  apps/remix-ide/src/assets/img/ht-latest-features.webp
  libs/remix-ui/home-tab/src/lib/components/homeTabFeatured.tsx
  release-process.md
Labels: ready-to-review

#4286 Solidity copilot improvements
  apps/remix-ide/src/app/plugins/copilot/suggestion-service/copilot-suggestion.ts
  apps/remix-ide/src/app/plugins/copilot/suggestion-service/suggestion-service.ts
  apps/remix-ide/src/app/tabs/locales/en/settings.json
  libs/remix-ui/editor/src/lib/providers/inlineCompletionProvider.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
Labels: ready-to-review, qa

#4288 update gpt text in terminal
  libs/remix-ui/terminal/src/lib/terminalWelcome.tsx
Labels: ready-to-review, qa
