Repository remix-project-org/remix-project, pull requests merged in 2023-06, with the labels that each got.

#3747 add l2 plug icon back
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
Labels: UDapp plugin, ready-to-review

#3758 fix matomo tracking ids
  apps/remix-ide/src/assets/js/loader.js
Labels: analytics

#3759 fix matomo ids
  apps/remix-ide-e2e/src/tests/remixd.test.ts
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
  apps/remix-ide/src/assets/js/loader.js
Labels: analytics

#3760 bump beta version to 0.33.2
  package.json
Labels: remix-beta

#3750 Enable proxy contract verification in Etherscan plugin
  apps/etherscan/src/app/RemixPlugin.tsx
  apps/etherscan/src/app/app.tsx
  apps/etherscan/src/app/types/Receipt.ts
  apps/etherscan/src/app/utils/utilities.ts
  apps/etherscan/src/app/utils/verify.ts
  apps/etherscan/src/app/views/ReceiptsView.tsx
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan, documentation-needed

#3770 publish remix-tests
  libs/remix-tests/package.json
Labels: remix-tests

#3642 Solhint linter plugin
  apps/remix-ide-e2e/src/tests/contract_flattener.test.ts
  apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
  apps/remix-ide/project.json
  apps/remix-ide/src/remixAppManager.js
  apps/solhint/package.json
  apps/solhint/project.json
  apps/solhint/src/app/App.tsx
  apps/solhint/src/app/SolhintPluginClient.ts
  apps/solhint/src/favicon.ico
  apps/solhint/src/index.html
  apps/solhint/src/main.tsx
  apps/solhint/src/profile.json
  apps/solhint/tsconfig.app.json
  apps/solhint/tsconfig.json
  apps/solhint/webpack.config.js
  apps/solhint/yarn.lock
  libs/remix-ui/checkbox/src/lib/remix-ui-checkbox.tsx
  libs/remix-ui/static-analyser/src/lib/Button/StaticAnalyserButton.tsx
  libs/remix-ui/static-analyser/src/lib/actions/staticAnalysisActions.ts
  libs/remix-ui/static-analyser/src/lib/components/BasicTitle.tsx
  libs/remix-ui/static-analyser/src/lib/reducers/staticAnalysisReducer.ts
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
  libs/remix-ui/static-analyser/src/staticanalyser.d.ts
  libs/remix-ui/vertical-icons-panel/src/lib/components/Badge.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/IconList.tsx
Labels: ready-to-review

#3771 update verify script to support proxy contract verification
  apps/etherscan/src/app/RemixPlugin.tsx
  apps/etherscan/src/app/utils/scripts.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  apps/remix-ide/src/app/tabs/locales/es/filePanel.json
  apps/remix-ide/src/app/tabs/locales/fr/filePanel.json
  apps/remix-ide/src/app/tabs/locales/zh/filePanel.json
  libs/remix-ui/workspace/src/lib/scripts/etherscan/receiptGuidScript.ts
  libs/remix-ui/workspace/src/lib/scripts/etherscan/verifyScript.ts
Labels: ready-to-review, etherscan

#3795 Debugger update Generated Sources tooltip
  apps/remix-ide/src/app/tabs/locales/en/debugger.json
Labels: UI

#3822 fix index in udapp
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
Labels: bug

#3816 Remove slither result before doing another analysis
  libs/remixd/src/services/slitherClient.ts
Labels: bug

#3817 show toaster only when etherscan plugin is active
  apps/etherscan/src/app/views/CaptureKeyView.tsx
  apps/etherscan/src/app/views/HomeView.tsx
  apps/etherscan/src/app/views/ReceiptsView.tsx
Labels: ready-to-review, etherscan

#3833 Debugger generated sources tooltip update tooltip postion
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
Labels: autorebase

#3836 add/remove plugins
  apps/remix-ide/src/app/tabs/analysis-tab.js
  apps/remix-ide/src/app/tabs/locales/en/home.json
  apps/remix-ide/src/assets/img/cookbook.webp
  libs/remix-ui/home-tab/src/lib/components/homeTabFeaturedPlugins.tsx
Labels: autorebase

#3842 Etherscan UX improvements
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan

#3807 improvements in pride theme and fixing an issue in SUT
  apps/remix-ide/src/assets/css/themes/remix-unicorn.css
  libs/remix-ui/solidity-unit-testing/src/lib/solidity-unit-testing.tsx
Labels: bug

#3838 Ssa Qa Fixes
  apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
  apps/remix-ide/src/app/tabs/analysis-tab.js
  apps/solhint/src/app/SolhintPluginClient.ts
  libs/remix-ui/static-analyser/src/lib/actions/staticAnalysisActions.ts
  libs/remix-ui/static-analyser/src/lib/components/BasicTitle.tsx
  libs/remix-ui/static-analyser/src/lib/reducers/staticAnalysisReducer.ts
  libs/remix-ui/static-analyser/src/lib/remix-ui-static-analyser.tsx
  libs/remix-ui/static-analyser/src/staticanalyser.d.ts
  libs/remix-ui/vertical-icons-panel/src/lib/components/Badge.tsx
Labels: ready-to-review

#3861 update constructor arguments section
  apps/etherscan/src/app/views/VerifyView.tsx
Labels: ready-to-review, etherscan
