Repository remix-project-org/remix-project, pull requests merged in 2023-02, with the labels that each got.

#3347 Nx
  .circleci/config.yml
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/project.json
  apps/remix-ide/src/app/plugins/remixd-handle.tsx
  apps/remix-ide/webpack.config.js
  package.json
  yarn.lock
Labels: remix-beta

#3345 fix compilation details
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
Labels: ready-to-review

#3352 Nx for master branch
  .circleci/config.yml
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/project.json
  apps/remix-ide/src/app/plugins/remixd-handle.tsx
  apps/remix-ide/webpack.config.js
  package.json
  yarn.lock
Labels: CI

#3338 fix issue 3216
  apps/remix-ide/src/app/tabs/locale-module.js
Labels: translation

#3342 fix sending tx with the api
  apps/remix-ide/src/blockchain/blockchain.js
  libs/remix-lib/src/execution/txRunner.ts
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-lib/src/execution/txRunnerWeb3.ts
Labels: bugfix, ready-to-review

#3314 Replace ganache provider with Remix simulator provider
  libs/ghaction-helper/package.json
  libs/ghaction-helper/src/methods.ts
Labels: next release, ready-for-review

#3251 Fix deps ethereujs/vm
  apps/remix-ide/src/app/tabs/runTab/model/recorder.js
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/providers/injected.js
  apps/remix-ide/src/blockchain/providers/node.js
  apps/remix-ide/src/blockchain/providers/vm.js
  apps/remix-ide/src/lib/helper.js
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-core-plugin/src/lib/compiler-fetch-and-compile.ts
  libs/remix-debug/package.json
  libs/remix-debug/src/code/disassembler.ts
  libs/remix-debug/src/solidity-decoder/types/ArrayType.ts
  libs/remix-debug/src/solidity-decoder/types/DynamicByteArray.ts
  libs/remix-debug/src/solidity-decoder/types/Mapping.ts
  libs/remix-debug/src/solidity-decoder/types/util.ts
  libs/remix-debug/test/decoder/stateTests/mapping.ts
  libs/remix-debug/test/vmCall.ts
  libs/remix-lib/package.json
  libs/remix-lib/src/execution/txFormat.ts
  libs/remix-lib/src/execution/txListener.ts
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-lib/src/execution/typeConversion.ts
  libs/remix-lib/src/hash.ts
  libs/remix-lib/src/helpers/txResultHelper.ts
  libs/remix-lib/src/index.ts
  libs/remix-lib/src/util.ts
  libs/remix-lib/test/txResultHelper.ts
  libs/remix-simulator/package.json
  libs/remix-simulator/src/VmProxy.ts
  libs/remix-simulator/src/methods/accounts.ts
  libs/remix-simulator/src/methods/transactions.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-ui/debugger-ui/src/lib/vm-debugger/global-variables.tsx
  libs/remix-ui/debugger-ui/src/utils/solidityTypeFormatter.ts
  libs/remix-ui/helper/src/lib/remix-ui-helper.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
  libs/remix-ui/run-tab/src/lib/components/value.tsx
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  package.json
  yarn.lock
Labels: ready-to-review

#3362 set default solidity compiler to v0.8.18 and add paris EVM
  apps/remix-ide/ci/makeMockCompiler.js
  apps/solidity-compiler/src/app/compiler.ts
  libs/remix-solidity/src/compiler/types.ts
  libs/remix-ui/editor/src/lib/remix-plugin-types.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
  package.json
Labels: solidity compiler plugin, ready-to-review

#3356 Refactor how providers are added to udapp
  apps/remix-ide-e2e/src/commands/connectToExternalHttpProvider.ts
  apps/remix-ide-e2e/src/tests/debugger.test.ts
  apps/remix-ide-e2e/src/tests/etherscan_api.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide-e2e/src/tests/providers.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/providers/abstract-provider.tsx
  apps/remix-ide/src/app/providers/basic-injected-provider.tsx
  apps/remix-ide/src/app/providers/external-http-provider.tsx
  apps/remix-ide/src/app/providers/foundry-provider.tsx
  apps/remix-ide/src/app/providers/ganache-provider.tsx
  apps/remix-ide/src/app/providers/hardhat-provider.tsx
  apps/remix-ide/src/app/providers/injected-L2-provider.tsx
  apps/remix-ide/src/app/providers/injected-arbitrum-one-provider.tsx
  apps/remix-ide/src/app/providers/injected-optimism-provider.tsx
  apps/remix-ide/src/app/providers/injected-provider.tsx
  apps/remix-ide/src/app/providers/vm-provider.tsx
  apps/remix-ide/src/app/tabs/abstract-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/blockchain.js
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/blockchain/providers/vm.js
  apps/remix-ide/src/remixAppManager.js
  libs/remix-lib/src/execution/txListener.ts
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/blockchain.d.ts
  libs/remix-ui/run-tab/src/lib/types/execution-context.d.ts
  libs/remix-ui/run-tab/src/lib/types/index.ts
  libs/remix-ui/terminal/src/lib/components/Context.tsx
  libs/remix-ui/terminal/src/lib/components/RenderCall.tsx
  libs/remix-ui/terminal/src/lib/components/RenderKnownTransactions.tsx
  libs/remix-ui/terminal/src/lib/components/RenderUnknownTransactions.tsx
Labels: ready-to-review

#3366 Flattener patch
  libs/remix-ui/solidity-compiler/src/lib/logic/flattenerUtilities.ts
  yarn.lock
Labels: ready-for-review

#3367 exclude initial msgs to matomo
  apps/remix-ide/src/assets/js/loader.js
Labels: remix-beta, ready-to-review

#3375 bump to v0.30.1
  package.json
Labels: remix-beta

#3358 download folder from FE
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/workspace/src/lib/utils/index.ts
Labels: file-explorer, ready-to-review

#3378 Improve VM forking
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/providers/abstract-provider.tsx
  apps/remix-ide/src/app/providers/custom-vm-fork-provider.tsx
  apps/remix-ide/src/app/providers/goerli-vm-fork-provider.tsx
  apps/remix-ide/src/app/providers/sepolia-vm-fork-provider.tsx
  apps/remix-ide/src/app/providers/vm-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-simulator/src/genesis.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
Labels: ready-to-review

#3406 fix test
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
Labels: browser-tests

#3311 resolver use package-lock.json or yarn lock
  libs/remix-core-plugin/src/lib/compiler-content-imports.ts
  libs/remix-url-resolver/src/resolve.ts
Labels: ready-to-review

#3380 Delete all workspaces added in the workspaces hamburger
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide-e2e/src/tests/workspace_git.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  apps/remix-ide/src/app/tabs/locales/zh/filePanel.json
  libs/remix-ui/helper/src/lib/components/custom-dropdown.tsx
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger-item.tsx
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/css/remix-ui-workspace.css
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#3418 fix asking permission if metamask is locked
  apps/remix-ide/src/app/providers/injected-provider.tsx
Labels: fix, autorebase

#3433 fix copy bytecode
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
Labels: solidity compiler plugin, bugfix

#3435 remove the notification in sendAsync
  apps/remix-ide/src/app/providers/injected-provider.tsx
Labels: ready-to-review

#3437 Set the provider only when it is initiated
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  apps/remix-ide/src/blockchain/providers/vm.js
  apps/remix-ide/src/blockchain/providers/worker-vm.ts
Labels: fix, ready-to-review

#3452 bump dev version to 0.32.0
  package.json
Labels: ready-to-review
