Repository remix-project-org/remix-project, pull requests merged in 2024-06, with the labels that each got.

#4818 fix vertical alignment of Transaction button
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: ready-to-review

#4833 set solidity v0.8.26 as latest
  apps/remix-ide/src/assets/list.json
  package.json
Labels: solidity compiler plugin

#4835 completion message updated for years time unit
  libs/remix-ui/editor/src/lib/providers/completion/completionGlobals.ts
Labels: editor, ready-to-review

#4816 Tooltip update for copy address
  apps/remix-ide/src/app/tabs/locales/en/udapp.json
  apps/remix-ide/src/app/tabs/locales/es/udapp.json
  apps/remix-ide/src/app/tabs/locales/fr/udapp.json
  apps/remix-ide/src/app/tabs/locales/it/udapp.json
  apps/remix-ide/src/app/tabs/locales/ru/udapp.json
  apps/remix-ide/src/app/tabs/locales/zh/udapp.json
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
Labels: ready-to-review, tooltip

#4827 export server
  libs/remix-simulator/bin/ethsim
  libs/remix-simulator/src/index.ts
  libs/remix-simulator/src/provider.ts
  libs/remix-simulator/src/server.ts
Labels: ready-to-review

#4831 add Korean to the UI
  apps/remix-ide/src/app/tabs/locale-module.js
  apps/remix-ide/src/app/tabs/locales/ko/circuit.json
  apps/remix-ide/src/app/tabs/locales/ko/debugger.json
  apps/remix-ide/src/app/tabs/locales/ko/filePanel.json
  apps/remix-ide/src/app/tabs/locales/ko/home.json
  apps/remix-ide/src/app/tabs/locales/ko/index.js
  apps/remix-ide/src/app/tabs/locales/ko/panel.json
  apps/remix-ide/src/app/tabs/locales/ko/permissionHandler.json
  apps/remix-ide/src/app/tabs/locales/ko/pluginManager.json
  apps/remix-ide/src/app/tabs/locales/ko/remixApp.json
  apps/remix-ide/src/app/tabs/locales/ko/remixUiTabs.json
  apps/remix-ide/src/app/tabs/locales/ko/search.json
  apps/remix-ide/src/app/tabs/locales/ko/settings.json
  apps/remix-ide/src/app/tabs/locales/ko/solidity.json
  apps/remix-ide/src/app/tabs/locales/ko/solidityUnitTesting.json
  apps/remix-ide/src/app/tabs/locales/ko/terminal.json
  apps/remix-ide/src/app/tabs/locales/ko/udapp.json
  libs/remix-ui/home-tab/src/lib/components/homeTablangOptions.tsx
Labels: translation

#4880 Add matomo for circom
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
Labels: ready-to-review

#4841 Fix get solidity version for udapp docs
  apps/remix-ide-e2e/src/tests/file_explorer_context_menu.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/instanceContainerUI.tsx
  libs/remix-ui/run-tab/src/lib/components/universalDappUI.tsx
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
Labels: ready-to-review

#4868 Update tooltips and toaster for solidity and udapp
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/deploy.ts
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/components/gasLimit.tsx
  libs/remix-ui/run-tab/src/lib/components/instanceContainerUI.tsx
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
  libs/remix-ui/static-analyser/src/lib/Button/StaticAnalyserButton.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
Labels: ready-to-review

#4885 Updates to Vyper plugin
  apps/remix-ide-e2e/src/commands/addFileSnekmate.ts
  apps/remix-ide-e2e/src/tests/vyper_api.test.ts
  apps/vyper/src/app/app.tsx
  apps/vyper/src/app/utils/remix-client.tsx
Labels: WIP

#4817 fixes in Grid view and updates for remix guide
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/plugins/remixGuide.tsx
  apps/remix-ide/src/app/plugins/remixGuideData.json
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/grid-view/src/lib/components/customCheckbox.tsx
  libs/remix-ui/grid-view/src/lib/filtersContext.tsx
  libs/remix-ui/grid-view/src/lib/remix-ui-grid-cell.css
  libs/remix-ui/grid-view/src/lib/remix-ui-grid-cell.tsx
  libs/remix-ui/grid-view/src/lib/remix-ui-grid-section.tsx
  libs/remix-ui/grid-view/src/lib/remix-ui-grid-view.tsx
Labels: ready-to-review

#4903 Remove conssole Log in vyper plugin
  apps/vyper/src/app/app.tsx
Labels: ready-to-review

#4910 Catch error for sign message
  libs/remix-ui/run-tab/src/lib/actions/account.ts
Labels: fix

#4930 Statusbar git section fix
  libs/remix-ui/statusbar/src/lib/components/gitStatus.tsx
Labels: ready-to-review

#4933 run tests on master
  apps/remix-ide-e2e/src/tests/etherscan_api.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy_injected.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
Labels: browser-tests
