Repository remix-project-org/remix-project, pull requests merged in 2024-08, with the labels that each got.

#5043 Circom Trusted Setup UI
  apps/circuit-compiler/src/app/actions/constant.ts
  apps/circuit-compiler/src/app/actions/index.ts
  apps/circuit-compiler/src/app/app.tsx
  apps/circuit-compiler/src/app/components/actions.tsx
  apps/circuit-compiler/src/app/components/compileBtn.tsx
  apps/circuit-compiler/src/app/components/configToggler.tsx
  apps/circuit-compiler/src/app/components/configurations.tsx
  apps/circuit-compiler/src/app/components/container.tsx
  apps/circuit-compiler/src/app/components/feedback.tsx
  apps/circuit-compiler/src/app/components/options.tsx
  apps/circuit-compiler/src/app/components/r1csBtn.tsx
  apps/circuit-compiler/src/app/components/setupExports.tsx
  apps/circuit-compiler/src/app/components/setupExportsBtn.tsx
  apps/circuit-compiler/src/app/components/toggler.tsx
  apps/circuit-compiler/src/app/components/witness.tsx
  apps/circuit-compiler/src/app/components/witnessToggler.tsx
  apps/circuit-compiler/src/app/reducers/state.ts
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/circuit-compiler/src/app/types/index.ts
  apps/circuit-compiler/src/css/app.css
  apps/circuit-compiler/src/profile.json
  apps/remix-ide-e2e/src/tests/circom.test.ts
  apps/remix-ide/src/app/tabs/locales/en/circuit.json
Labels: ready-to-review

#5070 Fix issue with bottom of Debugger
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.css
  libs/remix-ui/debugger-ui/src/lib/debugger-ui.tsx
Labels: ready-to-review

#5090 Add matomo check
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
Labels: analytics

#5075 persist providers
  apps/remix-ide-e2e/src/commands/pinGrid.ts
  apps/remix-ide-e2e/src/commands/switchEnvironment.ts
  apps/remix-ide-e2e/src/tests/grid.test.ts
  apps/remix-ide-e2e/src/tests/plugin_api.ts
  apps/remix-ide/src/blockchain/blockchain.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: ready-to-review

#5140 add Matomo
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: remix-beta

#5141 Bump beta version to 0.53.1
  package.json
Labels: remix-beta

#4979 Show log in github from FE
  apps/remix-ide-e2e/src/tests/dgit_github.test.ts
  apps/remix-ide-e2e/src/tests/dgit_local.test.ts
  apps/remix-ide-e2e/src/tests/workspace_git.test.ts
  apps/remix-ide/src/app/files/dgitProvider.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  apps/remix-ide/src/app/tabs/locales/en/git.json
  libs/remix-ui/app/src/index.ts
  libs/remix-ui/app/src/lib/remix-app/actions/app.ts
  libs/remix-ui/app/src/lib/remix-app/context/context.tsx
  libs/remix-ui/app/src/lib/remix-app/interface/index.ts
  libs/remix-ui/app/src/lib/remix-app/reducer/app.ts
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/app/src/lib/remix-app/state/app.ts
  libs/remix-ui/git/src/components/github/devicecode.tsx
  libs/remix-ui/git/src/components/gitui.tsx
  libs/remix-ui/git/src/components/panels/githubcredentials.tsx
  libs/remix-ui/git/src/components/panels/init.tsx
  libs/remix-ui/git/src/components/panels/setup.tsx
  libs/remix-ui/git/src/lib/gitactions.ts
  libs/remix-ui/git/src/lib/listeners.ts
  libs/remix-ui/git/src/types/index.ts
  libs/remix-ui/workspace/src/lib/css/file-explorer.css
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
Labels: ready-to-review

#5149 fix icon for L2 bridges in Udapp
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
Labels: UDapp plugin, ready-to-review
