Repository remix-project-org/remix-project, pull requests merged in 2024-04, with the labels that each got.

#4645 Vyper improvement patches.
  apps/remix-ide-e2e/src/tests/sol2uml.test.ts
  apps/remix-ide-e2e/src/tests/vyper_api.test.ts
  apps/vyper/src/app/app.tsx
  apps/vyper/src/app/components/CompilerButton.tsx
  apps/vyper/src/app/utils/compiler.tsx
Labels: ready-to-review

#4693 Update run-tab.tsx
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
Labels: UI

#4703 Reset state root for gas estimate calls and use calls
  libs/remix-lib/src/execution/txRunnerVM.ts
Labels: fix, ready-to-review

#4698 chore: fix some typos in conments
  apps/learneth/README.md
  libs/remix-debug/src/cmdline/index.ts
  libs/remix-debug/src/storage/storageViewer.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: autorebase

#4726 add create2 factory
  apps/remix-ide-e2e/src/tests/workspace.test.ts
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/components/workspace-hamburger.tsx
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/script-templates/create2-solidity-factory/create2-factory.sol
  libs/remix-ws-templates/src/script-templates/create2-solidity-factory/index.ts
Labels: e2e-tests-needed, ready-to-review

#4742 fix pinning for injected provider
  libs/remix-ui/run-tab/src/lib/actions/events.ts
Labels: UDapp plugin, ready-to-review

#4761 Update udapp.json tooltip
  apps/remix-ide/src/app/tabs/locales/en/udapp.json
Labels: translation
