Repository remix-project-org/remix-project, pull requests merged in 2024-09, with the labels that each got.

#5085 removed scam alerts in Desktop IDE (issue #4740)
  libs/remix-ui/statusbar/src/lib/remixui-statusbar-panel.tsx
Labels: remix-desktop

#5150 add forked chain in env explorer
  apps/remix-ide/src/app/providers/environment-explorer.tsx
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/blockchain/blockchain.tsx
Labels: ready-to-review

#5184 v0.54.0 release highlights
  releaseDetails.json
Labels: ready-to-review

#5178 Vyper compiler updates
  apps/remix-ide-e2e/src/tests/vyper_api.test.ts
  apps/vyper/src/app/components/CompilerButton.tsx
  apps/vyper/src/app/utils/compiler.tsx
  apps/vyper/src/app/utils/remix-client.tsx
Labels: ready-to-review

#5227 Bump beta version to 0.54.1
  package.json
Labels: remix-beta
