Repository remix-project-org/remix-project, pull requests merged in 2024-03, with the labels that each got.

#4566 Terminal UI
  apps/remix-ide-e2e/src/commands/openFile.ts
  libs/remix-ui/panel/src/lib/plugins/panel.css
  libs/remix-ui/terminal/src/lib/components/remix-ui-terminal-bar.tsx
  libs/remix-ui/terminal/src/lib/components/remix-ui-terminal-menu-buttons.css
  libs/remix-ui/terminal/src/lib/components/remix-ui-terminal-menu-buttons.tsx
  libs/remix-ui/terminal/src/lib/components/remix-ui-terminal-menu.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal-wrapper.tsx
  libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
  libs/remix-ui/terminal/src/lib/types/terminalTypes.ts
  libs/remix-ui/xterm/src/lib/components/remix-ui-terminal-menu-xterm.tsx
  libs/remix-ui/xterm/src/lib/components/remix-ui-xterm.tsx
  libs/remix-ui/xterm/src/lib/components/remix-ui-xterminals.tsx
  libs/remix-ui/xterm/src/lib/components/xterm-wrap.tsx
  libs/remix-ui/xterm/src/lib/css/index.css
Labels: UI, remix-desktop, Terminal, ready-to-review

#4599 Fix indents
  libs/remix-ui/workspace/src/lib/components/flat-tree.tsx
Labels: ready-to-review

#4585 Vyper UI Patch 003
  apps/remix-ide/src/app/panels/tab-proxy.js
  apps/remix-ide/src/assets/img/vyperLogo2.webp
  apps/vyper/src/app/app.css
  apps/vyper/src/app/app.tsx
  apps/vyper/src/app/components/CompileErrorCard.tsx
  apps/vyper/src/app/components/VyperResult.tsx
  apps/vyper/src/app/utils/compiler.tsx
  apps/vyper/src/app/utils/remix-client.tsx
  libs/remix-ui/solidity-compiler/src/lib/api/compiler-api.ts
Labels: ready-to-review

#4529 Save VM State and Blocks
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide/src/app/tabs/locales/en/settings.json
  apps/remix-ide/src/app/tabs/locales/es/settings.json
  apps/remix-ide/src/app/tabs/locales/fr/settings.json
  apps/remix-ide/src/app/tabs/locales/it/settings.json
  apps/remix-ide/src/app/tabs/locales/zh/settings.json
  apps/remix-ide/src/app/tabs/web3-provider.js
  apps/remix-ide/src/blockchain/blockchain.tsx
  apps/remix-ide/src/blockchain/execution-context.js
  apps/remix-ide/src/blockchain/providers/vm.ts
  apps/remix-ide/src/blockchain/providers/worker-vm.ts
  libs/remix-lib/src/execution/logsManager.ts
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-simulator/src/methods/transactions.ts
  libs/remix-simulator/src/provider.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
  libs/remix-ui/settings/src/lib/settingsReducer.ts
Labels: ready

#4652 Default to cancun
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide-e2e/src/tests/solidityUnittests.test.ts
  apps/remix-ide/src/blockchain/execution-context.js
Labels: ready-to-review
