Repository remix-project-org/remix-project, pull requests merged in 2024-01, with the labels that each got.

#4393 Fix Matomo (beta)
  apps/remix-ide/src/app/tabs/settings-tab.tsx
  apps/remix-ide/src/assets/js/loader.js
  libs/remix-ui/app/src/lib/remix-app/components/modals/matomo.tsx
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/settings/src/lib/settingsAction.ts
Labels: remix-beta

#4394 Bump beta version to 0.39.1
  package.json
Labels: remix-beta

#4182 vyper: use apeworx
  apps/remix-ide-e2e/src/commands/clickLaunchIcon.ts
  apps/remix-ide-e2e/src/commands/connectToExternalHttpProvider.ts
  apps/remix-ide-e2e/src/commands/createContract.ts
  apps/remix-ide-e2e/src/tests/vyper_api.test.ts
  apps/remix-ide-e2e/src/types/index.d.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/plugins/copilot/suggestion-service/copilot-suggestion.ts
  apps/remix-ide/src/app/plugins/copilot/suggestion-service/suggestion-service.ts
  apps/remix-ide/src/app/plugins/vyper-compilation-details.tsx
  apps/remix-ide/src/remixAppManager.js
  apps/vyper/src/app/app.css
  apps/vyper/src/app/app.tsx
  apps/vyper/src/app/components/CompilerButton.tsx
  apps/vyper/src/app/components/LocalUrl.tsx
  apps/vyper/src/app/components/VyperResult.tsx
  apps/vyper/src/app/utils/compiler.tsx
  apps/vyper/src/app/utils/remix-client.tsx
  apps/vyper/src/app/utils/types.ts
  libs/remix-ui/solidity-compile-details/src/lib/components/solidityCompile.tsx
  libs/remix-ui/solidity-compile-details/src/lib/solidity-compile-details.tsx
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
  libs/remix-ui/vyper-compile-details/src/index.ts
  libs/remix-ui/vyper-compile-details/src/lib/vyper-compile-details.tsx
  libs/remix-ui/vyper-compile-details/src/lib/vyperCompile.tsx
  package.json
  tsconfig.paths.json
  yarn.lock
Labels: autorebase, ready-to-review

#4400 fix terminal details
  libs/remix-ui/terminal/src/lib/components/Table.tsx
Labels: bugfix, ready-to-review

#4406 fix uniswap template naming
  apps/remix-ide/src/app/tabs/locales/en/filePanel.json
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#4420 remove compiler version number
  apps/vyper/src/app/app.tsx
Labels: UI, need i18n

#4457 Check if workspace exists
  apps/remix-ide/src/app/files/workspaceFileProvider.js
Labels: ready-to-review

#4481 Show Circom Log in Terminal and AskGPT for errors/warnings
  apps/circuit-compiler/src/app/components/container.tsx
  apps/circuit-compiler/src/app/components/feedback.tsx
  apps/circuit-compiler/src/app/components/feedbackAlert.tsx
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/circuit-compiler/src/app/types/index.ts
  package.json
  yarn.lock
Labels: autorebase

#4447 win build sign
  .circleci/config.yml
  apps/remixdesktop/package.json
Labels: remix-desktop

#4485 Fix gist
  apps/remix-ide-e2e/src/tests/gist.test.ts
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
Labels: bug, autorebase

#4494 set latest solidity compiler version to 0.8.24
  apps/remix-ide/ci/makeMockCompiler.js
  apps/solidity-compiler/src/app/compiler.ts
  libs/remix-solidity/src/compiler/types.ts
  libs/remix-ui/editor/src/lib/remix-plugin-types.ts
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/compileTabLogic.ts
  libs/remix-ui/solidity-compiler/src/lib/solidity-compiler.tsx
Labels: solidity compiler plugin, ready-to-review

#4456 Fix handling modal blur
  libs/remix-ui/modal-dialog/src/lib/remix-ui-modal-dialog.tsx
Labels: ready-to-review
