Repository remix-project-org/remix-project, pull requests merged in 2024-10, with the labels that each got.

#5243 fix at address button enabling
  libs/remix-ui/run-tab/src/lib/components/contractDropdownUI.tsx
Labels: ready-to-review

#5287 Update run-tab.js (add gnosis main)
  apps/remix-ide/src/app/udapp/run-tab.js
  apps/remix-ide/src/assets/img/gnosis_chain.png
Labels: ready-to-review

#5303 doc-gen is hidde from the plugin manager
  apps/remix-ide/src/remixAppManager.js
Labels: plugins

#5312 Fix rpc endpoint properties
  apps/remix-ide/src/app/providers/injected-arbitrum-one-provider.tsx
  apps/remix-ide/src/app/providers/injected-custom-provider.tsx
  apps/remix-ide/src/app/providers/injected-ephemery-testnet-provider.tsx
  apps/remix-ide/src/app/providers/injected-optimism-provider.tsx
  apps/remix-ide/src/app/providers/injected-provider-trustwallet.tsx
  apps/remix-ide/src/app/providers/injected-skale-chaos-testnet-provider.tsx
  apps/remix-ide/src/app/udapp/run-tab.tsx
Labels: ready-to-review

#5350 Contract verification plugin search chain fix for beta
  apps/contract-verification/src/app/components/SearchableChainDropdown.tsx
Labels: remix-beta

#5352 apply patch
  apps/remix-dapp/src/utils/txRunner.ts
  apps/remix-ide-e2e/src/commands/hideMetaMaskPopup.ts
  apps/remix-ide-e2e/src/tests/metamask.test.ts
  apps/remix-ide-e2e/src/tests/providers.test.ts
  apps/remix-ide/src/app/providers/abstract-provider.tsx
  apps/remix-ide/src/app/tabs/web3-provider.js
  apps/remix-ide/src/app/udapp/run-tab.tsx
  apps/remix-ide/src/blockchain/blockchain.tsx
  libs/remix-lib/src/execution/txRunnerWeb3.ts
  libs/remix-ui/run-tab/src/lib/actions/deploy.ts
Labels: remix-beta

#5353 Bump beta version 0.56.1
  package.json
Labels: remix-beta
