Repository remix-project-org/remix-project, pull requests merged in 2024-11, with the labels that each got.

#5361 hide module resolution error
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: ready-to-review

#5360 use the default evmVersion.
  apps/remix-ide/src/app/plugins/parser/services/code-parser-compiler.ts
Labels: bugfix, ready-to-review

#5401 make height adjustment
  apps/remix-ide/src/app/components/popup-panel.tsx
  apps/remix-ide/src/app/plugins/remixAIPlugin.tsx
  libs/remix-ui/remix-ai/src/lib/components/color.css
Labels: ready-to-review

#5437 bump beta version to 0.57.2
  package.json
Labels: remix-beta
