Repository remix-project-org/remix-project, pull requests merged in 2024-02, with the labels that each got.

#4518 fix address copy for external provider
  apps/remix-ide-e2e/src/tests/ballot.test.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_14.test.ts
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
Labels: autorebase

#4511 fix errors while contract deployment using script
  apps/remix-ide/src/app/tabs/web3-provider.js
  apps/remix-ide/src/blockchain/providers/injected.ts
  apps/remix-ide/src/blockchain/providers/node.ts
  apps/remix-ide/src/blockchain/providers/vm.ts
  libs/remix-simulator/src/methods/accounts.ts
Labels: ready-to-review

#4525 Vyper Contract compile FE
  apps/remix-ide-e2e/src/tests/vyper_api.test.ts
  apps/remix-ide/src/remixAppManager.js
  apps/vyper/src/app/app.tsx
  apps/vyper/src/app/components/CompilerButton.tsx
  apps/vyper/src/app/utils/compiler.tsx
  apps/vyper/src/app/utils/remix-client.tsx
  apps/vyper/src/profile.json
  libs/remix-ui/vyper-compile-details/src/lib/vyper-compile-details.tsx
  libs/remix-ui/vyper-compile-details/src/lib/vyperCompile.tsx
Labels: WIP

#4539 fix click on disable button border
  libs/remix-ui/run-tab/src/lib/components/contractGUI.tsx
Labels: ready-to-review

#4560 VYPER PATCH 002
  apps/remix-ide/src/app/tabs/locales/en/remixUiTabs.json
  apps/vyper/src/app/utils/remix-client.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: WIP
