Repository remix-project-org/remix-project, pull requests merged in 2024-12, with the labels that each got.

#5228 Circom desktop
  .circleci/config.yml
  .gitignore
  apps/circuit-compiler/src/app/actions/index.ts
  apps/circuit-compiler/src/app/app.tsx
  apps/circuit-compiler/src/app/components/configurations.tsx
  apps/circuit-compiler/src/app/components/container.tsx
  apps/circuit-compiler/src/app/components/generateProof.tsx
  apps/circuit-compiler/src/app/components/versions.tsx
  apps/circuit-compiler/src/app/reducers/state.ts
  apps/circuit-compiler/src/app/services/circomPluginClient.ts
  apps/circuit-compiler/src/app/types/index.ts
  apps/circuit-compiler/src/css/app.css
  apps/remix-ide-e2e/src/tests/circom.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/plugins/electron/circomElectronPlugin.ts
  apps/remix-ide/src/remixAppManager.js
  apps/remix-ide/src/remixEngine.js
  apps/remixdesktop/src/engine.ts
  apps/remixdesktop/src/plugins/circomElectronBasePlugin.ts
  apps/remixdesktop/src/preload.ts
  apps/remixdesktop/src/tools/circom.ts
  apps/remixdesktop/test/tests/app/circom-compiler.test.ts
  apps/remixdesktop/test/tests/app/circom-script.test.ts
  libs/remix-api/src/lib/plugins/remixAIDesktop-api.ts
  libs/remix-ws-templates/src/templates/hashchecker/scripts/groth16/groth16_zkproof.ts
  libs/remix-ws-templates/src/templates/hashchecker/scripts/plonk/plonk_zkproof.ts
  libs/remix-ws-templates/src/templates/rln/scripts/groth16/groth16_zkproof.ts
  libs/remix-ws-templates/src/templates/rln/scripts/plonk/plonk_zkproof.ts
  libs/remix-ws-templates/src/templates/semaphore/scripts/groth16/groth16_zkproof.ts
  libs/remix-ws-templates/src/templates/semaphore/scripts/plonk/plonk_zkproof.ts
Labels: remix-desktop, ready-to-review, circom

#5404 UDapp account dropdown refactor
  apps/remix-ide-e2e/src/commands/selectAccount.ts
  apps/remix-ide-e2e/src/commands/switchEnvironment.ts
  apps/remix-ide-e2e/src/tests/ballot_0_4_14.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
  apps/remix-ide-e2e/src/tests/transactionExecution.test.ts
  libs/remix-ui/helper/src/lib/components/custom-dropdown.tsx
  libs/remix-ui/run-tab/src/lib/components/account.tsx
Labels: ready-to-review

#5534 fix meta mask test
  apps/remix-ide-e2e/src/tests/metamask.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy_injected.test.ts
  apps/remix-ide-e2e/src/tests/terminal.test.ts
Labels: ready-to-review

#5492 noir icon added
  apps/remix-ide/src/assets/fontawesome/css/all.css
  apps/remix-ide/src/assets/fontawesome/webfonts/custom-icons.ttf
  apps/remix-ide/src/assets/fontawesome/webfonts/custom-icons.woff2
Labels: UX
