Repository remix-project-org/remix-project, pull requests merged in 2024-05, with the labels that each got.

#4796 Hometab PluginSection Patch
  apps/remix-ide/src/app/components/vertical-icons.tsx
Labels: ready-to-review

#4802 bring back rocket icon for bridges
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
Labels: UDapp plugin

#4787 enabled AI setting restore
  apps/remix-ide/src/app/tabs/settings-tab.tsx
  libs/remix-ui/settings/src/lib/remix-ui-settings.tsx
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: ready-to-review

#4808 fix hover blinking on enable AI icon
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: UX, Home Tab

#4798 Pinned panel
  apps/remix-ide-e2e/src/tests/layout.test.ts
  apps/remix-ide-e2e/src/tests/url.test.ts
  apps/remix-ide/src/app.js
  apps/remix-ide/src/app/components/panel.ts
  apps/remix-ide/src/app/components/pinned-panel.tsx
  apps/remix-ide/src/app/components/side-panel.tsx
  apps/remix-ide/src/app/panels/layout.ts
  apps/remix-ide/src/app/tabs/locales/en/panel.json
  apps/remix-ide/src/app/tabs/locales/es/panel.json
  apps/remix-ide/src/app/tabs/locales/fr/panel.json
  apps/remix-ide/src/app/tabs/locales/it/panel.json
  apps/remix-ide/src/app/tabs/locales/ru/panel.json
  apps/remix-ide/src/app/tabs/locales/zh/panel.json
  apps/remix-ide/src/app/tabs/state-logger.js
  apps/remix-ide/src/assets/list.json
  apps/remix-ide/src/remixAppManager.js
  libs/remix-ui/app/src/lib/remix-app/components/dragbar/dragbar.tsx
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/app/src/lib/remix-app/style/remix-app.css
  libs/remix-ui/debugger-ui/src/lib/api/debugger-api.ts
  libs/remix-ui/panel/src/lib/main/main-panel.tsx
  libs/remix-ui/panel/src/lib/plugins/panel-header.tsx
  libs/remix-ui/panel/src/lib/plugins/panel-plugin.tsx
  libs/remix-ui/panel/src/lib/plugins/remix-ui-panel.tsx
  libs/remix-ui/panel/src/lib/types/index.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  libs/remix-ui/search/src/lib/components/Search.tsx
  libs/remix-ui/search/src/lib/context/context.tsx
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: ready-to-review

#4814 Fix Contract Flattener Recursion bug
  apps/remix-ide/src/app/plugins/contractFlattener.tsx
  libs/remix-ui/solidity-compiler/src/lib/logic/flattenerUtilities.ts
Labels: ready-to-review

#4828 update font awesome kit
  apps/remix-ide/src/assets/fontawesome/css/all.css
  apps/remix-ide/src/assets/fontawesome/webfonts/custom-icons.ttf
  apps/remix-ide/src/assets/fontawesome/webfonts/custom-icons.woff2
Labels: UI
