Repository remix-project-org/remix-project, pull requests merged in 2024-07, with the labels that each got.

#4962 min width for default buttons of modals
  libs/remix-ui/modal-dialog/src/lib/remix-ui-modal-dialog.css
Labels: UI

#4983 Fix deployment to gh-pages.
  apps/remix-ide/ci/deploy_from_travis_remix-alpha.sh
  apps/remix-ide/ci/deploy_from_travis_remix-beta.sh
  apps/remix-ide/ci/deploy_from_travis_remix-live.sh
  apps/remix-ide/ci/gh-actions-deploy.yml
Labels: ready-to-review

#4767 Add Multiselect dragdrop Feature
  apps/remix-ide-e2e/src/commands/selectFiles.ts
  apps/remix-ide-e2e/src/tests/file_explorer_multiselect.test.ts
  apps/remix-ide/src/app/files/fileManager.ts
  libs/remix-ui/workspace/src/lib/actions/index.ts
  libs/remix-ui/workspace/src/lib/components/file-explorer.tsx
  libs/remix-ui/workspace/src/lib/components/flat-tree-drop.tsx
  libs/remix-ui/workspace/src/lib/components/flat-tree.tsx
  libs/remix-ui/workspace/src/lib/contexts/index.ts
  libs/remix-ui/workspace/src/lib/css/file-explorer.css
  libs/remix-ui/workspace/src/lib/providers/FileSystemProvider.tsx
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
  libs/remix-ui/workspace/src/lib/utils/getEventTarget.ts
Labels: ready-to-review

#4976 FE Delete & Rename shortcut keys
  libs/remix-ui/workspace/src/lib/components/file-explorer.tsx
  libs/remix-ui/workspace/src/lib/components/flat-tree.tsx
  libs/remix-ui/workspace/src/lib/types/index.ts
Labels: ready-to-review

#4960 Status bar updates
  libs/remix-ui/statusbar/src/contexts/statusbarcontext.tsx
  libs/remix-ui/statusbar/src/css/statusbar.css
  libs/remix-ui/statusbar/src/lib/components/aiStatus.tsx
  libs/remix-ui/statusbar/src/lib/components/didYouKnow.tsx
  libs/remix-ui/statusbar/src/lib/components/gitStatus.tsx
  libs/remix-ui/statusbar/src/lib/components/scamAlertStatus.tsx
  libs/remix-ui/statusbar/src/lib/components/scamDetails.tsx
  libs/remix-ui/statusbar/src/lib/remixui-statusbar-panel.tsx
  libs/remix-ui/statusbar/src/lib/types/index.ts
  libs/remix-ui/statusbar/src/utils/index.ts
Labels: ready-to-review, UX Meeting

#5008 Matomo: code paste
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: ready-to-review

#4999 Improve multi select drag and drop implementation
  libs/remix-ui/workspace/src/lib/components/flat-tree-drop.tsx
  libs/remix-ui/workspace/src/lib/components/flat-tree.tsx
  libs/remix-ui/workspace/src/lib/utils/getEventTarget.ts
Labels: ready-to-review

#4996 Do not put the URL in the path
  libs/remix-url-resolver/src/resolve.ts
Labels: ready-to-review

#5011 v0.52.0 release highlights
  releaseDetails.json
Labels: ready-to-review

#5014 increase timeout for contentImport
  apps/remix-ide/src/remixEngine.js
Labels: ready-to-review

#5018 Fix raw log styling
  libs/remix-ui/terminal/src/lib/components/Table.tsx
Labels: ready-to-review

#5020 fix git section font size
  libs/remix-ui/statusbar/src/lib/components/gitStatus.tsx
Labels: ready-to-review
