Repository remix-project-org/remix-project, pull requests merged in 2025-02, with the labels that each got.

#5652 Scriptrunner as main plugin
  apps/remix-ide-e2e/src/tests/script-runner.test.ts
  apps/remix-ide/src/app.ts
  apps/remix-ide/src/app/components/plugin-manager-component.js
  apps/remix-ide/src/app/panels/tab-proxy.js
  apps/remix-ide/src/app/plugins/script-runner-bridge.tsx
  apps/remix-ide/src/app/tabs/script-runner-ui.tsx
  libs/remix-ui/scriptrunner/src/lib/script-runner-ui.tsx
  libs/remix-ui/scriptrunner/src/types/index.ts
  libs/remix-ui/tabs/src/lib/remix-ui-tabs.tsx
Labels: incomplete

#5761 update discord invite
  libs/remix-ui/home-tab/src/lib/components/homeTabTitle.tsx
Labels: UX, incomplete

#5758 fix metamask signing
  apps/remix-ide/src/blockchain/providers/injected.ts
Labels: autorebase, ready-to-review

#5778 Workspace Dropdown Fix
  libs/remix-ui/workspace/src/lib/remix-ui-workspace.tsx
Labels: ready-to-review

#5792 Fix Vyper repo cloning issue
  apps/vyper/src/app/utils/remix-client.tsx
  yarn.lock
Labels: ready-to-review, incomplete

#5747 Fix loading deps which use module name remapping
  apps/remix-ide-e2e/src/tests/solidityImport.test.ts
  libs/remix-url-resolver/src/resolve.ts
Labels: autorebase, ready-to-review

#5793 Metamask Blockscout test
  apps/remix-ide-e2e/src/tests/metamask.test.ts
  apps/remix-ide-e2e/src/tests/runAndDeploy_injected.test.ts
  apps/remix-ide/src/blockchain/blockchain.tsx
Labels: ready-to-review

#5794 Fix metamask throwing errors
  apps/remix-ide/src/app/tabs/web3-provider.js
Labels: bugfix, ready-to-review

#5802 Do not load stealth drop
  apps/remix-ide/src/app/plugins/templates-selection/templates.ts
Labels: ready-to-review

#5791 Update LICENSE
  LICENSE
Labels: incomplete
