Repository remix-project-org/remix-project, pull requests merged in 2025-04, with the labels that each got.

#5614 create safe smart account
  apps/remix-dapp/src/locales/en/udapp.json
  apps/remix-ide/src/app/tabs/locales/en/udapp.json
  apps/remix-ide/src/blockchain/blockchain.tsx
  libs/remix-lib/src/execution/txFormat.ts
  libs/remix-lib/src/execution/txRunner.ts
  libs/remix-lib/src/execution/txRunnerWeb3.ts
  libs/remix-simulator/src/methods/txProcess.ts
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/components/settingsUI.tsx
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  package.json
  yarn.lock
Labels: ready-to-review, translation

#5927 artifact creation fixed
  libs/remix-core-plugin/src/lib/compiler-metadata.ts
Labels: ready-to-review

#5949 rabby wallet doesn't allow querying the genesis hash
  apps/remix-ide/src/blockchain/execution-context.js
Labels: bugfix

#5952 Remix guide update
  apps/remix-ide/src/app/plugins/remixGuideData.json
Labels: UX

#5971 fix solidity SCan URLs on remix beta
  libs/remix-ui/solidity-compiler/src/lib/contract-selection.tsx
Labels: remix-beta
