Repository remix-project-org/remix-project, pull requests merged in 2025-05, with the labels that each got.

#5988 Eip 7702
  apps/remix-dapp/src/locales/en/udapp.json
  apps/remix-ide-e2e/package.json
  apps/remix-ide-e2e/src/tests/eip7702.test.ts
  apps/remix-ide/src/app.ts
  apps/remix-ide/src/app/plugins/templates-selection/templates.ts
  apps/remix-ide/src/app/providers/vm-provider.tsx
  apps/remix-ide/src/app/tabs/locales/en/udapp.json
  apps/remix-ide/src/app/tabs/web3-provider.js
  apps/remix-ide/src/app/udapp/run-tab.tsx
  apps/remix-ide/src/blockchain/blockchain.tsx
  libs/ghaction-helper/package.json
  libs/remix-analyzer/package.json
  libs/remix-astwalker/package.json
  libs/remix-debug/package.json
  libs/remix-debug/src/code/codeResolver.ts
  libs/remix-lib/package.json
  libs/remix-lib/src/execution/txExecution.ts
  libs/remix-lib/src/execution/txRunner.ts
  libs/remix-lib/src/execution/txRunnerVM.ts
  libs/remix-lib/src/execution/txRunnerWeb3.ts
  libs/remix-lib/src/helpers/eip7702Constants.ts
  libs/remix-lib/src/index.ts
  libs/remix-simulator/package.json
  libs/remix-simulator/src/methods/accounts.ts
  libs/remix-simulator/src/methods/blocks.ts
  libs/remix-simulator/src/methods/transactions.ts
  libs/remix-simulator/src/methods/txProcess.ts
  libs/remix-simulator/src/vm-context.ts
  libs/remix-simulator/test/blocks.ts
  libs/remix-solidity/package.json
  libs/remix-tests/package.json
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/index.ts
  libs/remix-ui/run-tab/src/lib/components/account.tsx
  libs/remix-ui/run-tab/src/lib/components/settingsUI.tsx
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
  libs/remix-ui/terminal/src/lib/components/Context.tsx
  libs/remix-ui/terminal/src/lib/components/RenderUnknownTransactions.tsx
  libs/remix-ui/workspace/src/lib/utils/constants.ts
  libs/remix-ws-templates/package.json
  libs/remix-ws-templates/src/index.ts
  libs/remix-ws-templates/src/templates/simpleEip7702/.prettierrc
  libs/remix-ws-templates/src/templates/simpleEip7702/README.md
  libs/remix-ws-templates/src/templates/simpleEip7702/contracts/Example7702.sol
  libs/remix-ws-templates/src/templates/simpleEip7702/index.ts
  package.json
  yarn.lock
Labels: ready-to-review

#6003 update invite
  CONTRIBUTING.md
  README.md
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
  libs/remix-ui/home-tab/src/lib/components/homeTabTitle.tsx
  team-best-practices.md
Labels: UX

#6005 fix providers loading
  apps/remix-ide/src/blockchain/blockchain.tsx
Labels: ready-to-review

#6017 fixes compiler config file overriding
  libs/remix-ui/solidity-compiler/src/lib/compiler-container.tsx
Labels: solidity compiler plugin, ready-to-review

#6028 Aimodal Features
  .gitignore
  .yalc/@nlux/core/README.md
  .yalc/@nlux/core/cjs/nlux-core.js
  .yalc/@nlux/core/esm/nlux-core.js
  .yalc/@nlux/core/index.js
  .yalc/@nlux/core/nlux-core.d.ts
  .yalc/@nlux/core/package.json
  .yalc/@nlux/core/umd/nlux-core.js
  .yalc/@nlux/core/yalc.sig
  .yalc/@nlux/highlighter/README.md
  .yalc/@nlux/highlighter/cjs/highlighter.js
  .yalc/@nlux/highlighter/dark-theme.css
  .yalc/@nlux/highlighter/esm/highlighter.js
  .yalc/@nlux/highlighter/highlighter.d.ts
  .yalc/@nlux/highlighter/index.js
  .yalc/@nlux/highlighter/light-theme.css
  .yalc/@nlux/highlighter/package.json
  .yalc/@nlux/highlighter/umd/highlighter.js
  .yalc/@nlux/highlighter/yalc.sig
  .yalc/@nlux/react/README.md
  .yalc/@nlux/react/cjs/nlux-react.js
  .yalc/@nlux/react/esm/nlux-react.js
  .yalc/@nlux/react/index.js
  .yalc/@nlux/react/nlux-react.d.ts
  .yalc/@nlux/react/package.json
  .yalc/@nlux/react/umd/nlux-react.js
  .yalc/@nlux/react/yalc.sig
  .yalc/@nlux/themes/luna.css
  .yalc/@nlux/themes/nova.css
  .yalc/@nlux/themes/package.json
  .yalc/@nlux/themes/unstyled.css
  .yalc/@nlux/themes/yalc.sig
  apps/remix-ide/src/app/plugins/remixAIPlugin.tsx
  apps/remix-ide/src/app/plugins/templates-selection/templates-selection-plugin.tsx
  apps/remix-ide/src/app/plugins/templates-selection/templates.ts
  libs/remix-ui/app/src/lib/remix-app/remix-app.tsx
  libs/remix-ui/remix-ai-assistant/src/lib/remix-ui-remix-ai-assistant.tsx
  libs/remix-ui/remix-ai/src/lib/components/Default.tsx
  libs/remix-ui/workspace/src/lib/actions/events.ts
  libs/remix-ui/workspace/src/lib/actions/workspace.ts
  package.json
  tsconfig.paths.json
  yalc.lock
  yarn.lock
Labels: ready-to-review

#6043 Update node.ts
  apps/remix-ide/src/blockchain/providers/node.ts
Labels: bug
