Repository remix-project-org/remix-project, pull requests merged in 2025-07, with the labels that each got.

#6141 Show network name and ticker
  apps/remix-ide/src/blockchain/blockchain.tsx
  apps/remix-ide/src/blockchain/execution-context.js
  libs/remix-ui/helper/src/lib/remix-ui-helper.ts
  libs/remix-ui/run-tab/src/lib/actions/account.ts
  libs/remix-ui/run-tab/src/lib/actions/events.ts
Labels: UDapp plugin

#6137 AI agent uses accept/reject
  apps/remix-ide/src/app/editor/editor.js
  apps/remix-ide/src/app/plugins/code-format.ts
  libs/remix-ai-core/src/agents/workspaceAgent.ts
  libs/remix-ui/editor/src/lib/helpers/showCustomDiff.ts
  libs/remix-ui/editor/src/lib/remix-ui-editor.tsx
Labels: ready-to-review

#6145 analytics for matomo AI modal
  libs/remix-ui/app/src/lib/remix-app/components/modals/managePreferences.tsx
  libs/remix-ui/app/src/lib/remix-app/components/modals/matomo.tsx
Labels: analytics, ready-to-review

#6154 Ai assist patch
  apps/remix-ide-e2e/src/tests/ai_panel.test.ts
  apps/remix-ide/src/app/plugins/remix-ai-assistant.tsx
  apps/remix-ide/src/app/plugins/remixAIPlugin.tsx
  apps/remix-ide/src/assets/img/remixai-logoAI-updated.webp
  apps/remix-ide/src/assets/img/remixai-logoDark.webp
  libs/remix-ai-core/src/agents/contractAgent.ts
  libs/remix-ai-core/src/agents/workspaceAgent.ts
  libs/remix-ui/app/src/lib/remix-app/components/modals/modal-wrapper.tsx
  libs/remix-ui/app/src/lib/remix-app/context/provider.tsx
  libs/remix-ui/app/src/lib/remix-app/interface/index.ts
  libs/remix-ui/app/src/lib/remix-app/reducer/modals.ts
  libs/remix-ui/app/src/lib/remix-app/types/index.ts
  libs/remix-ui/modal-dialog/src/lib/types/index.ts
  libs/remix-ui/remix-ai-assistant/src/components/chat.tsx
  libs/remix-ui/remix-ai-assistant/src/components/prompt.tsx
  libs/remix-ui/remix-ai-assistant/src/components/remix-ui-remix-ai-assistant.tsx
  libs/remix-ui/vertical-icons-panel/src/lib/components/Icon.tsx
Labels: ready-to-review

#6172 Remix AI Chat UI Patch
  libs/remix-ui/remix-ai-assistant/src/components/chat.tsx
  libs/remix-ui/remix-ai-assistant/src/components/prompt.tsx
  libs/remix-ui/remix-ai-assistant/src/components/remix-ui-remix-ai-assistant.tsx
  libs/remix-ui/remix-ai-assistant/src/css/remix-ai-assistant.css
Labels: ready-to-review

#6180 AI Chat Patch
  libs/remix-ui/remix-ai-assistant/src/components/chat.tsx
  libs/remix-ui/remix-ai-assistant/src/components/remix-ui-remix-ai-assistant.tsx
Labels: ready-to-review
