Repository remix-project-org/remix-project, pull requests merged in 2025-03, with the labels that each got.

#5739 spelling issue
  apps/contract-verification/src/index.html
Labels: spam

#5650 Move RemixAppManager and PluginManagerComponent to ts
  apps/circuit-compiler/src/app/components/container.tsx
  apps/noir-compiler/src/app/actions/index.ts
  apps/noir-compiler/src/app/components/container.tsx
  apps/noir-compiler/src/app/services/noirParser.ts
  apps/noir-compiler/webpack.config.js
  apps/remix-ide/.env.example
  apps/remix-ide/.gitignore
  apps/remix-ide/src/app.ts
  apps/remix-ide/src/app/components/plugin-manager-component.tsx
  apps/remix-ide/src/remixAppManager.ts
  apps/remix-ide/src/types/index.d.ts
  libs/remix-api/src/lib/remix-api.ts
  libs/remix-ui/editor/src/lib/remix-plugin-types.ts
  libs/remix-ui/helper/src/types/compilerTypes.ts
  libs/remix-ui/plugin-manager/src/types.d.ts
Labels: ready-to-review

#5878 fix no current selected account
  libs/remix-ui/run-tab/src/lib/actions/account.ts
Labels: bug

#5844 Fix Udapp Environment Label Dropdown bug
  apps/remix-ide-e2e/src/tests/runAndDeploy.test.ts
  apps/remix-ide/src/app/udapp/run-tab.tsx
  apps/remix-ide/src/assets/list.json
  libs/remix-ui/environment-explorer/src/lib/types/index.ts
  libs/remix-ui/run-tab/src/lib/components/dropdownLabel.tsx
  libs/remix-ui/run-tab/src/lib/components/environment.tsx
  libs/remix-ui/run-tab/src/lib/components/settingsUI.tsx
  libs/remix-ui/run-tab/src/lib/reducers/runTab.ts
  libs/remix-ui/run-tab/src/lib/run-tab.tsx
  libs/remix-ui/run-tab/src/lib/types/index.ts
Labels: ready-to-review

#5883 update discord invite
  libs/remix-ui/home-tab/src/lib/components/homeTabTitle.tsx
Labels: Home Tab

#5891 fix placeholder for API key in contract verification plugin
  apps/contract-verification/src/app/components/ConfigInput.tsx
Labels: bugfix, contract verification plugin

#5896 fixing recorder "run" btn behaviour
  libs/remix-ui/run-tab/src/lib/components/recorderCardUI.tsx
Labels: ready-to-review

#5918 Celo EVM Deploy update
  libs/remix-ui/run-tab/src/lib/actions/evmmap.ts
Labels: ready-to-review

#5919 Patch for evmmap for Celo
  libs/remix-ui/run-tab/src/lib/actions/evmmap.ts
Labels: remix-beta, ready-to-review

#5922 bump beta version to 0.62.1
  package.json
Labels: remix-beta
